### ISSUE TITLE
Publish option ExcludeObjectTypes not working with multiple values

### ISSUE THREAD

**Issue by pada57** [rr-wfm/MSBuild.Sdk.SqlProj#104]
hello

i have issue when setting option to drop objects not in source and trying to preserve security objects for instance Users and Views seems like after semi-column not take value, tried with quotes and double quotes without success. When setting one object type works!
```
 dotnet publish /p:TargetDatabaseName=API_clean /p:DropObjectsNotInSource=True /p:ExcludeObjectTypes=Users;Views /p:BlockOnPossibleDataLoss=False
...
Setting property DropObjectsNotInSource to value True
  Setting property ExcludeObjectTypes to value Users
...
 Dropping Permission...
  Dropping [dbo].[aaa]...
  Dropping [dbo].[V_aaaCustomer]...
...
```
With sqlpackage.exe it does work but use different sets of flags
```
    <DoNotDropRoutes>True</DoNotDropRoutes>
    <DoNotDropRules>True</DoNotDropRules>
    <DoNotDropUsers>True</DoNotDropUsers>
    <DoNotDropSignatures>True</DoNotDropSignatures>
```

thanks in advance for your help

**Comment by jmezach** [comment]
@pada57 Just a quick question, have you tried to put the `ExcludeObjectTypes` property in the project file and do you get the same problem there?

**Comment by pada57** [comment]
> @pada57 Just a quick question, have you tried to put the `ExcludeObjectTypes` property in the project file and do you get the same problem there?

yes same using ExcludeObjectTypes or DoNotDropObjectTypes on project file XML
i will use sqldeploy.exe anyway as not part of this project

**Comment by jmezach** [comment]
I did some digging into this issue and it looks like semicolon separators for these values are a bit problematic due to how they are parsed by shells. I have an implementation that works with comma's instead and that works just fine.

Technically that would be a breaking change though, but since this property (and others as well) can't be used currently I'd rather not make the fix for this a 2.0. @ErikEJ @jeffrosenberg What do you think?

**Comment by ErikEJ** [comment]
Is it not just a bug fix then?

**Comment by jmezach** [comment]
Yeah, except that if anyone had `DatabaseSpecification`, `DoNotDropObjectTypes` or `ExcludeObjectTypes ` in their project files using semi-colons they would now have to change that to be comma separated or it won't work anymore. But then again, it doesn't work currently so I guess we can treat this as a bug fix anyway. I'll send in a PR soon.

**Comment by ErikEJ** [comment]
Add a check for the presence of semicolons and throw?

**Comment by jmezach** [comment]
@ErikEJ That's not a bad idea actually ;). I'll add that in.
