### ISSUE TITLE
Fileglobs with Postdeploy scripts?

### ISSUE THREAD

**Issue by stobias123** [rr-wfm/MSBuild.Sdk.SqlProj#113]
I have a whole bunch of post deploy scripts, and the build tips over when I try to run with the shown config

```xml
    <ItemGroup>
	    <PostDeploy Include="Scripts/PostDeployment/**/*.sql" />
    </ItemGroup>
```

Is there a proper way for me to include the whole directory of post deploy scripts in one line?

**Comment by jeffrosenberg** [comment]
@stobias123 the build is only meant to handle one pre-deployment and one post-deployment script. This is the case for .sqlproj-style projects as well. However, you can reference a post-deployment script that then uses sqlcmd syntax to include other files, like so:

```sql
-- postdeploy.sql

-- commands to execute directly from your script
insert into MyTable
values (1, 2);

-- include additional files with this syntax
:r MyFirstScript.sql 
:r MySecondScript.sql
```

**Comment by jmezach** [comment]
I would like to add that we could of course add this as a feature, but I don't think that has much value since the order in which these scripts run is most likely important. With globs you don't have any control over their ordering so I don't think such a feature would make sense.
