### ISSUE TITLE
MSBuild.Sdk.SqlProj cannot find dotnet when installed in $HOME/.dotnet

### ISSUE THREAD

**Issue by sarvasana** [rr-wfm/MSBuild.Sdk.SqlProj#115]
I used the [`dotnet-install.sh`](https://dotnet.microsoft.com/download/dotnet-core/scripts) script provided by Microsoft to install version 3.1.405 of dotnet-core.

When I use Jetbrains Rider to compile a database project using `MSBuild.Sdk.SqlProj/1.11.1`, the build fails with the below error.   
It appears the MSBuild scripts fail to find the SDK.

When the SDK is installed at `/usr/share/dotnet` the problem goes away.

**Build Output:**
```
Build started 1/24/2021 11:46:35 PM.
Logging verbosity is set to: Normal.     1>Project "/home/kris/Projects/*****/****.Database/****.Database.csproj" on node 1 (build target(s)).
     1>ValidateEnvironment:
         Using target framework netcoreapp3.1 to run DacpacTool
       ResolveDatabaseReferences:
         Resolved dacpac file from package  to 
         Resolved database package references: 
       GetIncludedFiles:
         /tmp/tmpe93b181fc3f74b36bd7da2490dfa0a87.exec.cmd: line 2: dotnet: command not found
     1>/home/kris/.nuget/packages/msbuild.sdk.sqlproj/1.11.1/Sdk/Sdk.targets(151,5): error MSB3073: The command "dotnet "/home/kris/.nuget/packages/msbuild.sdk.sqlproj/1.11.1/Sdk/../tools/netcoreapp3.1/DacpacTool.dll" collect-includes   " exited with code 127.
     1>Done Building Project "/home/kris/Projects/****/****/****.Database/****.Database.csproj" (build target(s)) -- FAILED.

Build FAILED.
```

**Version Info:**
```
❯ which dotnet
/home/kris/.dotnet/dotnet
❯ echo $path
/home/kris/.asdf/shims /home/kris/.asdf/bin /home/kris/.dotnet /home/kris/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin
❯ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.405
 Commit:    65f9d75b1c

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/kris/.dotnet/sdk/3.1.405/

Host (useful for support):
  Version: 3.1.11
  Commit:  f5eceb8105

.NET Core SDKs installed:
  3.1.405 [/home/kris/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/home/kris/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/home/kris/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**System Info:**
OS: Manjaro Linux x86_64 
Host: 82A2 Yoga Slim 7 14ARE05 
Kernel: 5.10.7-3-MANJARO

**Comment by jeffrosenberg** [comment]
That's interesting... looking at the command being issued, it's just `dotnet`, without any sort of path qualifier.

I don't know anything about Manjaro Linux, but I notice that in your version info that you posted, you showed the value of the variable `$path`, as opposed to `$PATH`, and Linux is usually case-sensitive. Is `$path` really the right variable? Is it possible that it should be `$PATH`, and that it doesn't include the path to the dotnet executable?

**Comment by jmezach** [comment]
We pretty much assume that `dottnet` is on the PATH since I think you'd need to have that anyway to do something useful. That being said I think we could look at if we can find the path where `dotnet` is located based on properties available within MSBuild. I would expect MSBuild to have some kind of logic for that somewhere. That would make this a little bit more robust I guess.

**Comment by sarvasana** [comment]
> That's interesting... looking at the command being issued, it's just `dotnet`, without any sort of path qualifier.
> 
> I don't know anything about Manjaro Linux, but I notice that in your version info that you posted, you showed the value of the variable `$path`, as opposed to `$PATH`, and Linux is usually case-sensitive. Is `$path` really the right variable? Is it possible that it should be `$PATH`, and that it doesn't include the path to the dotnet executable?

Yes, I checked both $path and $PATH evaluate to the same value.

**Comment by jeffrosenberg** [comment]
> That being said I think we could look at if we can find the path where `dotnet` is located based on properties available within MSBuild. I would expect MSBuild to have some kind of logic for that somewhere. That would make this a little bit more robust I guess.

I would argue that this shouldn't be necessary, as we should be able to rely on the OS to know how to run `dotnet`. That said, I don't know what's going on here, it seems like it should work.

**Comment by sarvasana** [comment]
> We pretty much assume that `dottnet` is on the PATH since I think you'd need to have that anyway to do something useful. That being said I think we could look at if we can find the path where `dotnet` is located based on properties available within MSBuild. I would expect MSBuild to have some kind of logic for that somewhere. That would make this a little bit more robust I guess.

Then I suspect that somehow Rider is started on a shell different from the user shell and it is missing the path to dotnet on that shell.

**Comment by jeffrosenberg** [comment]
Yes, I bet that's what's going on here. Is `dotnet` being added to your path in a startup script such as `.bashrc` or `.profile`?

**Comment by sarvasana** [comment]
> Yes, I bet that's what's going on here. Is `dotnet` being added to your path in a startup script such as `.bashrc` or `.profile`?

No, the default user shell is `zsh` so I added it to `.zshrc`.
Not at the same machine currently, but I can test out adding it to `.bashrc` or `.profile` tomorrow again.

**Comment by sarvasana** [comment]
I added the following to `.profile`:

```
❯ cat .profile
export PATH=$HOME/.dotnet:$PATH
export DOTNET_ROOT="~/.dotnet"
export DOTNET_CLI_TELEMETRY_OPTOUT=true
```

Both `bash` and `sh` can now find `dotnet`:
```
❯ bash
[kris@manjaro ~]$ dotnet --version
3.1.405
[kris@manjaro ~]$ sh
sh-5.1$ dotnet --version
3.1.405
sh-5.1$ 
```

However, when building the database project from Jetbrains Rider, the build still fails with the same error, because it cannot find `dotnet`.

From diagnostics log I noticed that the dacpac tool is executed using the Exec task from Microsoft.Build.Tasks.Core.
Could it be that this task has no access to all the environment variables somehow?
Maybe it is possible to use the EnvironmentVariables property of this task to provide the path.

**Comment by jmezach** [comment]
I believe that you always get passed down any environment variables from the parent process, so I honestly don't know why it doesn't work. I'm not familiar with Rider personally but perhaps it has a means of generating an [MSBuild Binary Log](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/Binary-Log.md). That includes environment variables so that could give a clue as to what's happening.

**Comment by jmezach** [comment]
@sarvasana Haven't heard from you in a while. Is this still an issue? I'm going to go ahead and close this, but feel free to re-open if this is still an issue.
