### ISSUE TITLE
Build error when .NET 6 preview is installed.  Any suggestions to correct this is appreciated.

### ISSUE THREAD

**Issue by ChiefInnovator** [rr-wfm/MSBuild.Sdk.SqlProj#125]
We get the following error when Visual Studio 2019 Preview is installed on our workstation.  We tried using global.json to limit to only released versions, but no go.  Any thoughts on how to fix this?

global.json
{
  "sdk": {
    "allowPrerelease": false
  }
}

![image](https://user-images.githubusercontent.com/15870558/111459469-16a3b580-86f1-11eb-9827-5042fda3c946.png)

**Comment by ErikEJ** [comment]
Change your framework target to a supported one, like "net5.0"

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Richard Crane ***@***.***>
Sent: Wednesday, March 17, 2021 12:21:39 PM
To: rr-wfm/MSBuild.Sdk.SqlProj ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rr-wfm/MSBuild.Sdk.SqlProj] Build error when .NET 6 preview is installed. Any suggestions to correct this is appreciated. (#125)


We get the following error when Visual Studio 2019 Preview is installed on our workstation. We tried using global.json to limit to only released versions, but no go. Any thoughts on how to fix this?

global.json
{
"sdk": {
"allowPrerelease": false
}
}

[image]<https://user-images.githubusercontent.com/15870558/111459469-16a3b580-86f1-11eb-9827-5042fda3c946.png>

**Comment by jmezach** [comment]
@ChiefInnovator I would expect that global.json to fix this issue. Did you restart Visual Studio after adding the global.json? I believe it doesn't immediately take effect. If that doesn't work, could you share the output of `dotnet --info` running from the command line in the folder of your project?

**Comment by ratynchukD** [comment]
I had a similar issue but with "netcoreapp5.0"

Adding the global.json worked for me.
Example of the content:
```
{
  "sdk": {
    "version": "3.1.407"
  }
}
```

Find out more [here ](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#examples) about global.json

**Comment by jmezach** [comment]
@ratynchukD As of version 1.6.0 there should be support for .NET 5 so it would work with any SDK version 5.0. If that is not the case we would like to understand why it doesn't work for you.

We don't support .NET 6 previews just yet. Since .NET 6 is still early in the preview phase I don't expect many people will have an issue with this, but please upvote this issue if you feel this is important to you.

**Comment by ratynchukD** [comment]
@jmezach This needs to be discussed in my team since we are using the 1.2.0 version. I'm new to the project and might be the first who faced with the issue.

Regarding .NET 6 preview - I don't feel this is important to my team or me.

Thank you!

**Comment by jmezach** [comment]
I don't think there's much more we can do here so I'll go ahead and close this. If you feel there's still an issue here feel free to re-open.
