### ISSUE TITLE
Sqpackage 14.0 cannot deploy dacpac

### ISSUE THREAD

**Issue by iremezoff** [rr-wfm/MSBuild.Sdk.SqlProj#136]
First of all, Sqlpackage 15 handles dacpac-file properly. The issue comes to play only with sqlpackage version 14 privisioned by msi or SSMS 2017.
I have stumbled upon the following error during running deploy with dacpac file:
```
The Element or Annotation class SqlDatabaseOptions does not contain the Property class CatalogCollation.
```

My researches have led me to the reason: **model.xml** file contains `<Property Name="CatalogCollation" Value="0" />` line. After removing it (with hash recalculation in **origin.xml**) and making dacpac again deploy finishes successfully. 
Nothing with configuration has helped me. I tried to override _KnownModelProperties_ property on csproj without problem property - no result.
I compared **model.xml** file from original dacpac (produced from sqlproj) and didn't see there _CatalogCollation_ property. Also I noticed that _SchemaVersion_ is used by version 2.9 in contrast to 2.4 in dacpac from csproj file.

Versions:
MSBuild.Sdk.SqlProj 1.15.0
SqlServerVersion property 140
DotNet Sdk 3.1

**Comment by jmezach** [comment]
@iremezoff Thanks for reporting this. This is actually the first time I've heard of any compatibility issues between this project and `SqlPackage.exe`. In fact, we are happily deploying `.dacpac`'s build by this project using SqlPackage.exe 14. Would you mind sharing the exact version number of SqlPackage.exe?

**Comment by iremezoff** [comment]
Yes, of course. I installed dacfx by choco package manager (https://community.chocolatey.org/packages/sql2017-dacframework). The version is **14.0.3757.2**. By the way,  I saw comments for the same issue for sqlproj caused by buggy release of sqlpackge. The recommendation was to update build of the tool. Of course, in my case it wasn't feasible.

**Comment by jmezach** [comment]
Can you share a link to those comments?

**Comment by iremezoff** [comment]
https://dba.stackexchange.com/questions/208775/bacpac-import-fails-with-error-the-element-or-annotation-class-sqldatabaseoptio
https://techcommunity.microsoft.com/t5/azure-database-support-blog/what-will-happen-with-catalog-collation-and-case-sensitive-vs/ba-p/368978

**Comment by jmezach** [comment]
Right, so looking at the release notes for SqlPackage.exe it seems that [17.8](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver15#178-sqlpackage) is the latest version which has a version number of **14.0.4079.2**. That seems to be a newer version than the one you are using. Have you tried upgrading `SqlPackage.exe` to the latest version by upgrading the Microsoft® SQL Server® Data-Tier Application Framework to the [latest version](https://www.microsoft.com/en-us/download/details.aspx?id=57073)?

**Comment by iremezoff** [comment]
Nope, because of using certain version provided by choco repository. I will try and report here

**Comment by jmezach** [comment]
No problem. Glad it worked out!
