### ISSUE TITLE
Dacpac builder brings in ALL *.sql files which can produce errors

### ISSUE THREAD

**Issue by markalroberts** [rr-wfm/MSBuild.Sdk.SqlProj#137]
For example if you reference another project that has a SQL artefact generated from it, this SQL file gets copied into the bin folder  of the project and then gets included in the Dacpac.

The work around at the moment is to add a `Remove` for bin/obj folders.

It would be better perhaps if these folders where ignored by default.

**Comment by markalroberts** [comment]
Hmm turns out that some sensible amounts of sql _are_ excluded by default:

```
  <ItemGroup>
    <Content Include="**/*.sql">
      <Pack>False</Pack>
      <SuppressTSqlWarnings></SuppressTSqlWarnings>
    </Content>
    <Content Remove="Pre-Deployment/**/*.sql" />
    <Content Remove="Post-Deployment/**/*.sql" />
    <Content Remove="bin/**/*.sql" />
    <Content Remove="obj/**/*.sql" />
  </ItemGroup>
```

https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/d80ce593feb255471cf4b60e46a520e67b52bedb/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L39

**Comment by jeffrosenberg** [comment]
Oh man, the `git blame` says apparently I submitted that change 4 months ago and completely forgot! Sorry about that 🤦

**Comment by jmezach** [comment]
I don't think there's anything more we can do here so I'm going ahead and close this. If you feel there's still more to do here feel free to re-open.
