### ISSUE TITLE
PostDeployment scripts crash dacpac building

### ISSUE THREAD

**Issue by iremezoff** [rr-wfm/MSBuild.Sdk.SqlProj#143]
I've stumbled upon curious behaviour while using post/pre-deployments scripts.
I learnt https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/tree/master/test/TestProjectWithPrePost. When I had changed directory name of scripts from **Post-Deployment** to **PostDeployment** (without dash) the project stopped building, dotnet returned 
```
EXEC : error SQL71006: Only one statement is allowed per batch. A batch separator, such as 'GO', might be required between statements. [/Users/ivan/libs/MSBuild.Sdk.SqlProj/test/TestProjectWithPrePost/TestProjectWithPrePost.csproj]
/Users/ivan/.nuget/packages/msbuild.sdk.sqlproj/1.15.0/Sdk/Sdk.targets(231,5): error MSB3073: The command "dotnet "/Users/ivan/.nuget/packages/msbuild.sdk.sqlproj/1.15.0/Sdk/../tools/netcoreapp5.0/DacpacTool.dll" build -o "obj/Debug/netstandard2.0/TestProjectWithPrePost.dacpac" -n "TestProjectWithPrePost" -v "1.0.0" -sv Sql150 -i "obj/Debug/netstandard2.0/TestProjectWithPrePost.InputFiles.txt"   -p ServiceBrokerOption=EnableBroker -p RecoveryMode=Simple -p AllowSnapshotIsolation=True --predeploy Pre-Deployment/Script.PreDeployment.SimpleInclude.sql --postdeploy PostDeployment/Script.PostDeployment.sql --refactorlog RefactorLog/TestProjectWithPrePost.refactorlog     " exited with code 1. [/Users/ivan/libs/MSBuild.Sdk.SqlProj/test/TestProjectWithPrePost/TestProjectWithPrePost.csproj]
    0 Warning(s)
    2 Error(s)

```

I tried to add GO statement everywhere - nothing helped.
Does the feature depend on naming?

**Comment by ErikEJ** [comment]
Yes, it does, but agree it may not be clearly documented.

**Comment by iremezoff** [comment]
Is there an implicit reason?

**Comment by jmezach** [comment]
We exclude `.sql` files in `Pre-Deployment` and `Post-Deployment` files from the build by default since they are usually created by the templates and typically include scripts that cannot be used to create a model (which is ultimately what's in the `.dacpac`).

**Comment by iremezoff** [comment]
I'd add this explanation and note to readme.md. Very useful info,  I thought I got insane :)

**Comment by jmezach** [comment]
It is mentioned in the README actually, see: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#editing-the-project-file

**Comment by ErikEJ** [comment]
I see it in the docs now, just not in the pre/post deployment section.

**Comment by jmezach** [comment]
I've added some clarifications to the README on this subject, so I think we can close this now.
