### ISSUE TITLE
Generated script does not include referenced dacapac tables

### ISSUE THREAD

**Issue by dovic95** [rr-wfm/MSBuild.Sdk.SqlProj#144]
Hello,

I'am moving from my old `sqlproj` to the `csproj `SDK style with MSBuild.Sdk.SqlProj. Everything is working fine except that the generated script contains only my project tables and not the ones referenced via package reference

`MyDatabase `project looks like
```
<Project Sdk="MSBuild.Sdk.SqlProj/1.15.0">
    <PropertyGroup>
         <TargetFramework>netstandard2.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <SqlServerVersion>Sql130</SqlServerVersion>
    </PropertyGroup>

      <PropertyGroup>
        <IncludeCompositeObjects>True</IncludeCompositeObjects>
        <RunScriptsFromReferences>True</RunScriptsFromReferences>
        <GenerateCreateScript>True</GenerateCreateScript>
        <TargetDatabase>MyDatabase</TargetDatabase>
      </PropertyGroup>

      <ItemGroup>
        <Content Include="dbo\**" />
      </ItemGroup>

      <ItemGroup>
        <PackageReference Include="ExternalDatabase" Version="1.0.0" />
        <PackageReference Include="master" Version="110.0.0" DatabaseVariableLiteralValue="master" />
      </ItemGroup>

      <ItemGroup>
        <None Update="MyDatabase.nuspec">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
      </ItemGroup>

</Project>
```

`ExternalDatabase `is packaged in the same way

When I run `dotnet publish`, everything works fine. I have all the tables created (the ones in `MyDatabase `and the ones in `ExternalDatabase`)

The script `MyDatabase_Create.sql` however, contains only the `MyDatabase `tables

I tried many things but I'm unable to get a full creation script

Any help would be really appreciated :)

**Comment by dovic95** [comment]
Seems like the `IncludeCompositeObjects` parameter is not considered when generating the script

**Comment by jmezach** [comment]
@dovic95 Thank you for reporting. To be honest, I'm not sure whether this is by design and whether this behaves in the same way as with `.sqlproj` projects. @markalroberts might know since he's initially contributed this feature.

**Comment by dovic95** [comment]
I created a Pull request for fixing this: #224 

@jmezach yes it's working as expected with `.sqlproj` files.
