### ISSUE TITLE
Sqlpackage varibles for dotnet publish

### ISSUE THREAD

**Issue by iSeiryu** [rr-wfm/MSBuild.Sdk.SqlProj#158]
Is it possible to convert this
```bash
/opt/sqlpackage/sqlpackage \
    /a:Publish /sf:/src/$project/$project.build.dacpac \
    /tsn:tcp:localhost /tdn:$dbname /tu:sa /tp:$SA_PASSWORD \
    /Variables:DATA_DIR=/db /Variables:LOG_DIR=/db_logs \
    /pr:/src/$project/${project}_profile.publish.xml
```
to `dotnet publish`?
Specifically how can I pass `/Variables:my_variable` and a publish profile?

**Comment by jeffrosenberg** [comment]
@iSeiryu to be honest, our recommendation would be to keep using SqlPackage. We support `dotnet publish` as a shortcut for local dev, but per our readme, we recommend using SqlPackage for advanced scenarios. Since you're already using SqlPackage, I would suggest just sticking with that.

**Comment by ErikEJ** [comment]
We should remove support for publish!

**Comment by iSeiryu** [comment]
Lol
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/33#issuecomment-671020761
