### ISSUE TITLE
Is the SDK Compatible with .net5.0 . It is giving me an error for the same 

### ISSUE THREAD

**Issue by mayank-chaturvedi** [rr-wfm/MSBuild.Sdk.SqlProj#162]
`The current SDK bundles target framework 'netcoreapp5.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 2.1 or 3.1, or file an issue at https://github.com/jmezach/MSBuild.Sdk.SqlProj/ to add support.	Iit.BackOffice.CorporateActions.GoldenRecordsService.DBBuild	C:\Users\xmayc\.nuget\packages\msbuild.sdk.sqlproj\1.1.0\Sdk\Sdk.targets`

Halp!

**Comment by jmezach** [comment]
Looks like you're using version 1.1.0 of the SDK which didn't support .NET 5. Newer versions do, so try updating the SDK version at the top of your project file. You can find the latest version on NuGet.org.

**Comment by mayank-chaturvedi** [comment]
Yes ,Thank you. That fixed it. Browsing through old closed issues, I had found a similar problem which helped.
