### ISSUE TITLE
Is there a way to set DefaultDataPath and DefaultFilePrefix variables?

### ISSUE THREAD

**Issue by Condor2708** [rr-wfm/MSBuild.Sdk.SqlProj#200]
This is the csproj Variables  

```
<ItemGroup>
    <SqlCmdVariable Include="DefaultDataPath">
      <DefaultValue>/var/opt/mssql/data/</DefaultValue>
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
    <SqlCmdVariable Include="DefaultFilePrefix">
      <DefaultValue>I18n</DefaultValue>
      <Value>$(SqlCmdVar__2)</Value>
    </SqlCmdVariable>
  </ItemGroup>
```

C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\bin\Debug\netstandard2.0>sqlpackage /Action:Script /SourceFile:Kapsch.Internationalization.Database.MVP.dacpac /TargetServerName:localhost /TargetDatabaseName:I18n /TargetUser:usr_cs /TargetPassword:usr_cs /p:IncludeCompositeObjects=True /v:DefaultDataPath=/var/opt/mssql/data/ /v:DefaultFilePrefix="I18n" /OutputPath:c:\tmp\I18n.sql
Generating publish script for database 'I18n' on server 'localhost'.
*** An error occurred during deployment plan generation. Deployment cannot continue.
Missing values for the following SqlCmd variables:DefaultDataPath.
Time elapsed 00:00:02.57

**Comment by jmezach** [comment]
Hi @Condor2708, first of all, thanks for reporting this. I would expect this to work to be honest. Would you mind sharing the output of `dotnet build` on the MSBuild.Sdk.SqlProj project? That might give us some hints as to what is going wrong.

**Comment by Condor2708** [comment]
Hi @jmezach 
Here is the build output

```
1>------ Rebuild All started: Project: Kapsch.Internationalization.Database.MVP, Configuration: Debug Any CPU ------
Restored C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.CultureManager.Service\Kapsch.CultureManager.Service.csproj (in 705 ms).
1>Using package name Kapsch.Internationalization.Database.MVP and version 7.0.0.1
1>Using SQL Server version Sql150
1>Adding reference to C:\Users\sanchez\.nuget\packages\kapsch.internationalization.database\7.0.0.3/tools/Kapsch.Internationalization.Database.dacpac with external parts dbl=|dbv=|srv=
1>Adding SqlCmd variable DefaultDataPath
1>Adding SqlCmd variable DefaultFilePrefix
1>Writing model to C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\obj\Debug\netstandard2.0\Kapsch.Internationalization.Database.MVP.dacpac
1>Adding C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\Scripts\Script.PreDeployment.sql to package
1>Adding C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\Scripts\Script.PostDeployment.sql to package
1>Kapsch.Internationalization.Database.MVP -> C:\dev-net5\platform-mvp\culture\src\mvp\Kapsch.Internationalization.Database.MVP\bin\Debug\netstandard2.0\Kapsch.Internationalization.Database.MVP.dacpac
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by Condor2708** [comment]
My problem occurs because I want to add the following sql scripts in order to create FileGroup Files

/*
Do not change the database path or name variables.
Any sqlcmd variables will be properly substituted during 
build and deployment.
*/
ALTER DATABASE [$(DatabaseName)]
	ADD FILEGROUP [I18nData];

GO
/*
Do not change the database path or name variables.
Any sqlcmd variables will be properly substituted during 
build and deployment.
*/
ALTER DATABASE [$(DatabaseName)]
	ADD FILE
	(
		NAME = [I18nData],
		FILENAME = '$(DefaultDataPath)$(DefaultDataPath)_I18nData1.ndf'
	) TO FILEGROUP [I18nData];

GO

**Comment by jmezach** [comment]
If I remember correctly I believe that SqlPackage always adds the DefaultDataPath and DefaultFilePrefix SQLCMD variables to the resulting script, but I could be wrong. What happens if you remove the SQLCMD variables from your project, rebuild the `.dacpac` and then run the SqlPackage Script operation again and inspect the resulting script?

**Comment by Condor2708** [comment]
Another thing i've found -> 
If I remove SqlCmdVariables and deploy to a SQLEXPRESS installed on windows it works ok
The problem occurs when I am trying to deploy over an SQL hosted with a Docker Linux 

*** Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 5105, Level 16, State 2, Line 1 A file activation error occurred. The physical file name 'I18nData_1.ndf' may be incorrect. Diagnose and correct additional errors, and retry the operation.
Error SQL72045: Script execution error.  The executed script:
ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [I18nData], FILENAME = '$(DefaultDataPath)I18nData_1.ndf') TO FILEGROUP [I18nData];


Error SQL72014: .Net SqlClient Data Provider: Msg 5009, Level 16, State 8, Line 1 One or more files listed in the statement could not be found or could not be initialized.
Error SQL72045: Script execution error.  The executed script:
ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [I18nData], FILENAME = '$(DefaultDataPath)I18nData_1.ndf') TO FILEGROUP [I18nData];

**Comment by jmezach** [comment]
That's interesting. Are you using `/Action:Script` or `/Action:Publish` with SqlPackage?

**Comment by Condor2708** [comment]
Using Script option it generates the file ...but the DefautlDataPath is not filled

```
*
Deployment script for I18n

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "I18n"
:setvar DefaultFilePrefix "I18n"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
PRINT N'Creating [I18nData]...';


GO
ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [I18nData], FILENAME = '$(DefaultDataPath)I18nData_1.ndf') TO FILEGROUP [I18nData];


GO
PRINT N'Creating [I18nIndex]...';


GO
ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [I18nIndex], FILENAME = '$(DefaultDataPath)I18nIndex_1.ndf') TO FILEGROUP [I18nIndex];

```

**Comment by jeffrosenberg** [comment]
I may be misremembering, but I think those may actually be settings pulled from your server, rather than variables that can be passed at the cli. Also, out of curiosity, do you have the filegroups stored as objects in your database project, or are you actually storing the full `alter` script?

**Comment by Condor2708** [comment]
I am having the file and filegroups as objects in my db project.

**Comment by jmezach** [comment]
To be honest this looks more like an issue with SqlPackage than an issue with MSBuild.Sdk.SqlProj. Does it work correctly if you build the same project using a regular `.sqlproj`?

**Comment by Condor2708** [comment]
Same behaviour with .sqlproj project -> I think that the problem is that with linux is not detecting the correct values of DefaultDataPath

**Comment by Condor2708** [comment]
I think that I will add some prefix to the DefaultDataPath and DefaultFilePrefix  variables as a workaround

**Comment by jmezach** [comment]
If the issue also occurs with regular `.sqlproj`'s I think the issue should be reported at https://github.com/microsoft/DacFx/issues. There isn't much we can do about this from our side I'm afraid.
