### ISSUE TITLE
Both .sqlproj and .csproj needed + Project Reference not working

### ISSUE THREAD

**Issue by fpucheta** [rr-wfm/MSBuild.Sdk.SqlProj#204]
Hi!
I've been working for some time with Database Project, but I recently needed to implement a Jenkins CI/CD Pipeline on Linux, and there's when I found your project, which is amazing, but I'm having some issues implementing it.

What I want to achieve is referencing additional database objects (from a view, for example).

I read several questions, specially the one from Michael on [https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/108](url), but was not able to make it work.

I've created this solution (I've simplified them for testing purposes):

https://github.com/fpucheta/MSBuild.Sdk.SqlProj.ProjectReference

Doing build/publish from VS using .sqlproj works properly, but running through dotnet publish throws this error:

![image](https://user-images.githubusercontent.com/50141331/136228398-6c620555-6050-4a9f-9864-0a18b81d9f3d.png)

...UsersView.sql(2,27): error SQL71561: SqlView: [dbo].[UsersView] has an unresolved reference to object [$(SourceDatabase)].[dbo].[Users]. [C:\..\TargetDatabase.Build.csproj]
C:\...\UsersView.sql(2,20): warning SQL71563: The wildcard character in $(SourceDatabase).dbo.Users could not be expanded. [C:\...\TargetDatabase.Build.csproj]

I followed the steps present on the documentation, but probably I'm missing something.
Thanks in advance for your help!

Fernando

**Comment by jmezach** [comment]
After looking at this again I'm thinking this could very well be related to #201. Looking at the output it seems to fail while building the package, which makes sense since we don't pass in any values for the variable. Fixing #201 probably isn't that much work, but I'm fairly busy with other things at the moment.

**Comment by fpucheta** [comment]
@jmezach Thanks. Just in case, I was checking [#201](url), but there it's mentioned that the problem is with **dotnet build** but in my case if fails with both **dotnet build** and **dotnet publish**.

**Comment by fpucheta** [comment]
@ErikEJ Thanks for your comment [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/201#issuecomment-1326046480), ATM I don't remember what I've used, I'll check it again and do some new tests, and will keep you posted.

**Comment by fpucheta** [comment]
> @fpucheta Any updates?

@ErikEJ Thanks for the follow up, but no, we're moving to Github Actions now, so we'll probably not need this approach.
