### ISSUE TITLE
MSB4044 CopyRefAssembly error with v2 beta

### ISSUE THREAD

**Issue by BenjaminAbt** [rr-wfm/MSBuild.Sdk.SqlProj#222]
I updated to the latest beta and ran into

> /opt/hostedtoolcache/dotnet/sdk/6.0.100/Microsoft.Common.CurrentVersion.targets(4654,5): error MSB4044: The "CopyRefAssembly" task was not given a value for the required parameter "SourcePath". [/home/vsts/work/1/s/src/MyMssqlProjectFile.csproj]

```xml
<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0-beta.1">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <SqlServerVersion>SqlAzure</SqlServerVersion>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MyOwnAzureMasterV12" Version="150.0.0" DatabaseVariableLiteralValue="master" />
    </ItemGroup>

</Project>

```

I think that this case counts among the currently unsupported dependencies; but still the report as requested.

**Comment by BenjaminAbt** [comment]
because of https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/141 I added `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>` and it "works" (no error) for now

**Comment by jmezach** [comment]
@BenjaminAbt First of all, thanks for reporting this. I noticed that you're using `<TargetFramework>net6.0</TargetFramework>`. As per the README we've always recommended using `netstandard2.0` as the target framework. Do you get the same error if you're using that, without the `<ProduceReferenceAssembly>` flag?

**Comment by BenjaminAbt** [comment]
The recommendation since .NET 5 is to abandon the .NET Standard (idea was for adoption only) and switch to specific runtimes.
Wouldn't that therefore also be a good idea here?

**Comment by BenjaminAbt** [comment]
> I don't think .NET Standard is going away either, because it will still be needed for folks who have both .NET Framework and .NET (Core) applications and that want to share things.

https://www.codemag.com/Article/2010022/From-.NET-Standard-to-.NET-5 by Immo

* Use netstandard2.0 to share code between .NET Framework and all other platforms.
* Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.
* Use net5.0 for code sharing moving forward.

So it's probably a good idea to look straight ahead :-) But yes, this wont happen tomorrow.

> Perhaps though we should call this out more in the README.

An idea would also to print a warning, if netstandard is not used (for now)..?

> Do you get the same error if you're using that, without the <ProduceReferenceAssembly> flag

No, with `netstandard` the error does not appear. 
Thanks!
