### ISSUE TITLE
Trying to Deploy a temporal table via dacpac

### ISSUE THREAD

**Issue by mayank-chaturvedi** [rr-wfm/MSBuild.Sdk.SqlProj#223]
Hi,

I am trying to deploy a temporal table via dacpac to azure sql. It is giving me error while publishing the dacpac. Have tried to create the table and alter(set the system versioning in the post deployment script).
The script runs fine from SSMS. Could it be a pipeline permission issue or maybe i am missing something ?

The table i am trying to create :
_CREATE TABLE [Generic].[ABC] (
    [RuleId]       INT                                         NOT NULL,
    [UpdatedBy]    VARCHAR (100)                               NULL,
    [ValidFrom]    DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]      DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_Rules] PRIMARY KEY CLUSTERED ([RuleId] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[Generic].[ABCHistory], DATA_CONSISTENCY_CHECK=ON));_

And if i am moving to post deployment script :
_ALTER TABLE Generic.ABC
    SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = Generic.ABCHistory ,DATA_CONSISTENCY_CHECK = ON));_

Best Regards.
Mayank

**Comment by ErikEJ** [comment]
What error?

**Comment by mayank-chaturvedi** [comment]
We have an azure task created to deploy DACPAC on our sql pool instance: Unfortunately - It is eating up the error :
_2021-11-24T12:10:57.8170319Z Creating [Generic].[ABC]...
2021-11-24T12:10:57.9231791Z An error occurred while the batch was being executed.
2021-11-24T12:10:57.9350261Z Updating database (Failed)
2021-11-24T12:11:09.3022096Z ##[error]_

So this happens while trying to create to a table .

**Comment by jmezach** [comment]
@mayank-chaturvedi Are you using `SqlPackage.exe` for the deployment? Or are you using `dotnet publish`?

**Comment by mayank-chaturvedi** [comment]
@jmezach `SqlPackage.exe`

**Comment by ErikEJ** [comment]
What is "sql pool" ??

**Comment by mayank-chaturvedi** [comment]
Basically our DB on azure. 
We use [sql pool instance](https://docs.microsoft.com/en-us/azure/azure-sql/database/elastic-pool-overview) , soirry for not making it clear.

**Comment by jmezach** [comment]
This looks more lik an issue with the deployment and not necessarily related to MSBuild.Sdk.SqlProj. Perhaps you could try posting it at https://github.com/Microsoft/DacFx?.

**Comment by ErikEJ** [comment]
This is a sqlpackage / DacFX issue
