### ISSUE TITLE
Mute SQL warnings

### ISSUE THREAD

**Issue by Belorus** [rr-wfm/MSBuild.Sdk.SqlProj#228]
Hi everyone,

Is there a way to do subj?

I tried adding following to my .csproj, but it didn't help.
`<NoWarn>71562</NoWarn>`
Also i tried adding
`/p:nowarn=71562` to `dotnet build` and this didn't help

P.S. Thanks a ton for your work. We completely changed DB versioning approach thanks to your SDK

**Comment by jmezach** [comment]
@Belorus First of all, thank you for the encouragement, really means a lot!

I believe what you are looking for is `SuppressTSqlWarnings`. This is described in more detail in our [README](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#model-compiler-options), but you should be able to replace `<NoWarn>` with `<SuppressTSqlWarnings>` and it should work.

**Comment by ErikEJ** [comment]
@jmezach Why are you assigned?

**Comment by jmezach** [comment]
Probably because I already answered this. But let's go ahead and close this. @Belorus Feel free to re-open if this is still an issue.
