### ISSUE TITLE
Support NET6 combined with NET5 and netcore3.1

### ISSUE THREAD

**Issue by sarvasana** [rr-wfm/MSBuild.Sdk.SqlProj#229]
On a system without dotnet:

1. `curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin -c 3.1 --install-dir /usr/share/dotnet`
2. `sudo ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet`
3. `dotnet build` (result OK)
4. `curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin -c 5 --install-dir /usr/share/dotnet`
5. `dotnet build` (result OK)
6. `curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin -c LTS --install-dir /usr/share/dotnet`
7. `dotnet build` (result NOK)

/home/user/.nuget/packages/msbuild.sdk.sqlproj/1.11.4/Sdk/Sdk.targets(97,5): error : The current SDK bundles target framework 'netcoreapp6.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 2.1 or 3.1, or file an issue at https://github.com/jmezach/MSBuild.Sdk.SqlProj/ to add support. [/home/user/Projects/customer/apps/api/db/db.csproj]

**Comment by jmezach** [comment]
It looks like you were using version 1.11.4 which doesn't support .NET 6. We've added initial support for .NET 6 in our preview release 2.0.0-beta.1 which is up on NuGet.org for you to try. If you're still running into issues with that release feel free to post them here.

**Comment by sarvasana** [comment]
Yeah sorry, I noticed that too and then closed this issue, but forgot to comment on it.
Thanks for your reply. I noticed that there is a beta release that supports NET6.
How can I try that out?

**Comment by jmezach** [comment]
You should be able to update your project file to read:

```xml
<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0-beta.1">
```

**Comment by sarvasana** [comment]
Thanks will try that! Awesome work.

**Comment by ErikEJ** [comment]
When DacFX 16 hits RTM

**Comment by pmatrosov** [comment]
@jmezach DacFx already reached version 160.5400.1, waiting for 2.0.0 release :)

**Comment by jmezach** [comment]
You're right, not sure why we didn't get a dependabot PR updating that package though. But anyway, 2.0.0 is up on NuGet.org now :).
