### ISSUE TITLE
GenerateCreateScript: Set CreateNewDatabase to true

### ISSUE THREAD

**Issue by dovic95** [rr-wfm/MSBuild.Sdk.SqlProj#230]
Hello,

First, @jmezach and @jeffrosenberg thank you for accepting my pull request #224 

I tested the new version in my project and it now produces a generate script that includes tables from referenced `dacpac`s. The only 'issue' is the `CreateNewDatabase` property not set, the script does not create the database when I run it (I have to manually create the database first..). A bit annoying

I will propose a new pull request where the `CreateNewDatabase` can be set. The question is: Should we provide the possibility to set it through a property (name of this property?) or should it be always `true`?

**Comment by jmezach** [comment]
I'm starting to feel that for the `GenerateCreateScript` functionality we might want to pass along all the `    KnownDeployProperties` (see [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/5d12a407eeb7ca734d690417cc6a8ba2c64387f0/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L122)) because they could possibly all influence the outcome of the generated script and folks might want to set them.

**Comment by dovic95** [comment]
That makes sense. 

Should we provide the DeployOptions properties object to the [BuildDacpac](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/5d12a407eeb7ca734d690417cc6a8ba2c64387f0/src/DacpacTool/Program.cs#L76) method (so the different `KnownDeployProperties `will be provided) or should we create a specific `CommandHandler `for generating the script (that will run after `BuildDacpac`) ?

**Comment by jmezach** [comment]
We'll probably want to do it as part of building as that would probably be the fastest.

**Comment by rizi** [comment]
> We'll probably want to do it as part of building as that would probably be the fastest.

Does this mean a db is never created automatically? Or it won't be created when it comes from a referenced assembly?

I would like that a db should be created when it does not already exist, does this work at the moment? (we don't have references at the moment).

Br

**Comment by jmezach** [comment]
@rizi I believe that by default a new database is created if one doesn't exist. `CreateNewDatabase=True` basically means that if a database exists, it is dropped first and a new one is created.

**Comment by rizi** [comment]
> @rizi I believe that by default a new database is created if one doesn't exist. `CreateNewDatabase=True` basically means that if a database exists, it is dropped first and a new one is created.

Thank you very much for fast response!

Br

**Comment by dovic95** [comment]
@jmezach as pull request #244  was merged, could we release the version?

**Comment by jmezach** [comment]
@dovic95 I'm sorry, I have been really busy last week. I'll try to get it out this week.

**Comment by jmezach** [comment]
@dovic95 Version 1.17.3 is now up on NuGet which includes #244.

**Comment by dovic95** [comment]
Thanks @jmezach
