### ISSUE TITLE
Enable Docker for building dacpac files in container 

### ISSUE THREAD

**Issue by PrettySolution** [rr-wfm/MSBuild.Sdk.SqlProj#236]
Hello,
Can you please add an example project with a Dockerfile that will build dacpac files in docker?

**Comment by jeffrosenberg** [comment]
@PrettySolution to clarify, are you asking about using Docker to build a dacpac with MSBuild? Or to publish a previously-generated dacpac? Since MSBuild is cross-platform, not sure when the former would be needed, but there are doubtless use cases I'm not considering.

@jmezach if this is something you think would be valuable for our docs, I can write it up over the next few days.

**Comment by PrettySolution** [comment]
@jeffrosenberg 
I'd like to build a dacpac with MSBuild using Docker.
Thanks!

**Comment by jmezach** [comment]
I am curious about the use case here. I understand you want to build a `.dacpac` inside a container, but then where does the `.dacpac` go? A container image with just a `.dacpac` in it doesn't really make sense to me, but maybe I'm misunderstanding the question here?

**Comment by PrettySolution** [comment]
The `.dacpac` files will go to another `final` container with `sqlcmd` tool installed. The final image will be running on-demand when a new client DB needs to be provisioned. It's a kind of multi-tenancy solution.

**Comment by ngruson** [comment]
@PrettySolution : here's an example of a Dockerfile wherein `sqlpackage` is used to initialize a SQL database that is running in a container. The example is using a Linux image, don't know if it's helpful for you.  The `deploy.sql` that is produced is subsequently handled by a PowerShell script to create/update the database.
https://github.com/ngruson/AdventureWorks/blob/master/src/Services/Customer/src/AW.Services.Customer.Database.Build/Dockerfile

**Comment by PrettySolution** [comment]
Thanks a lot!
Merry Christmas!

**Comment by thealbres** [comment]
> @PrettySolution : here's an example of a Dockerfile wherein `sqlpackage` is used to initialize a SQL database that is running in a container. The example is using a Linux image, don't know if it's helpful for you. The `deploy.sql` that is produced is subsequently handled by a PowerShell script to create/update the database. https://github.com/ngruson/AdventureWorks/blob/master/src/Services/Customer/src/AW.Services.Customer.Database.Build/Dockerfile

Hi, I was trying to use this example of yours, but I end up with this error when I try to use the `build` function
![image](https://user-images.githubusercontent.com/80134809/156418956-b4bc3e35-a620-49be-9b6b-24b894c28492.png)

Have you faced something like that?

**Comment by ngruson** [comment]
> > @PrettySolution : here's an example of a Dockerfile wherein `sqlpackage` is used to initialize a SQL database that is running in a container. The example is using a Linux image, don't know if it's helpful for you. The `deploy.sql` that is produced is subsequently handled by a PowerShell script to create/update the database. https://github.com/ngruson/AdventureWorks/blob/master/src/Services/Customer/src/AW.Services.Customer.Database.Build/Dockerfile
> 
> Hi, I was trying to use this example of yours, but I end up with this error when I try to use the `build` function ![image](https://user-images.githubusercontent.com/80134809/156418956-b4bc3e35-a620-49be-9b6b-24b894c28492.png)
> 
> Have you faced something like that?

I don't recall seeing this error, but it looks like that you are trying to build your .sqlproj.
The Database.Build project in my example is actually a class library that is including files from the database project.
See also https://erikej.github.io/efcore/2020/05/11/ssdt-dacpac-netcore.html
