### ISSUE TITLE
Build in VS2022 fails

### ISSUE THREAD

**Issue by ngruson** [rr-wfm/MSBuild.Sdk.SqlProj#239]
I'm migrating a database project from VS2019 to VS2022. In VS2019, I was using version 1.15.0 of MSBuild.Sdk.SqlProj.
In VS2022, I've changed the version to 2.0.0-beta.1 and the target framework to NET 6. When I build the project, I get the error `The "CopyRefAssembly" task was not given a value for the required parameter "SourcePath".`
Is this supposed to work within VS2022? I'm not sure.

The project file looks like this:
```
<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0-beta.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <SqlServerVersion>Sql150</SqlServerVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\AW.Services.Customer.Database\**\Tables\*.sql" />
    <None Include="..\AW.Services.Customer.Database\**\Data\*.sql" />
    <PostDeploy Include="..\AW.Services.Customer.Database\**\Script.PostDeployment.sql" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="..\AW.Services.Customer.Database\obj\Debug\**" />
  </ItemGroup>
</Project>
```

**Comment by ErikEJ** [comment]
Try using netstandard2.0 instead.

**Comment by ngruson** [comment]
Thanks Erik, I had been trying with netstandard2.1, but using netstandard2.0 it works.

**Comment by jmezach** [comment]
@ErikEJ @jeffrosenberg Perhaps we should add that warning as also suggested in #222 to lead users to the pit of success.

**Comment by ErikEJ** [comment]
Good idea!
