### ISSUE TITLE
Objects not specified in csproj file getting added to dacpac

### ISSUE THREAD

**Issue by ashishmg-gds** [rr-wfm/MSBuild.Sdk.SqlProj#258]
Hi Team,

There is this weird thing happening with me. Why adding objects to dacpac , it not respecting the `csproj` file. All objects under my project folder is getting added to dacpac by default. Eg: I have not included any `PreDeploy` scripts in my csproj and yet `sql` under my predeployment folder is getting added.

**Comment by jmezach** [comment]
@ashishmg-gds By default we include all the`.sql` files that are in the same folder as your `.csproj` or any folder below. This is similar to how regular C# projects work these days. We do however exclude any `.sql` files in the `Pre-Deployment` and `Post-Deployment` folders (or any subfolder) as well as the `bin` and `obj` folders.

**Comment by jeffrosenberg** [comment]
To follow up on what @jmezach wrote above, you can exclude any files or folders from being included in the build by adding one or more `Content Remove` nodes such as the following:

```
<Content Remove="Directory\File.sql" />
<Content Remove="Directory\**\*.sql" />
```

**Comment by jmezach** [comment]
I think we have documented this pretty well in the README now, so I'm going to close this. Feel free to re-open though.
