### ISSUE TITLE
Post Deployment Script issue

### ISSUE THREAD

**Issue by greektreat** [rr-wfm/MSBuild.Sdk.SqlProj#260]
I Have followed the instructions to add a post deployment script and it fails to work what is wrong with the below code:

these are the pieces I added to the project 
```
	<PostDeploy Include="DeploymentScripts\Script.PostDeployment.sql" />
	<None Include="DeploymentScripts\Scripts\Event.SOFTSTOPEXCEPTION.sql" />
	<None Include="DeploymentScripts\Scripts\Task.DEFAULT_MANUAL_ACTIONREQUIRED_SHERLOCKTASK.sql" />
```

and in the post deployment script it self :
```

:r .\Scripts\Event.SOFTSTOPEXCEPTION.sql
:r .\Scripts\Task.DEFAULT_MANUAL_ACTIONREQUIRED_SHERLOCKTASK.sql

```

> 
> 1>Adding DeploymentScripts\Script.PostDeployment.sql to the model
> 1>Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> 1> ---> Microsoft.SqlServer.Dac.Model.DacModelException: Add or update objects failed due to the following errors:
> 1>EXEC : error SQL46010: Incorrect syntax near \.

**Comment by jmezach** [comment]
Thanks for reaching out! Could you try replacing what you currently have in your project file with the following:

```xml
<Content Remove="DeploymentScripts\**\*.sql" />
<PostDeploy Include="DeploymentScripts\Script.PostDeployment.sql" />
```

That way we make sure that none of the scripts underneath `DeploymentScripts` are added to the model directly, but instead included in the overall post-deployment script.

**Comment by greektreat** [comment]
> Thanks for reaching out! Could you try replacing what you currently have in your project file with the following:
> 
> ```
> <Content Remove="DeploymentScripts\**\*.sql" />
> <PostDeploy Include="DeploymentScripts\Script.PostDeployment.sql" />
> ```
> 
> That way we make sure that none of the scripts underneath `DeploymentScripts` are added to the model directly, but instead included in the overall post-deployment script.

Ahh! thank you, that fixed it. I thought I was going crazy
