### ISSUE TITLE
TargetPassword doesn't support Comma value

### ISSUE THREAD

**Issue by lvitti** [rr-wfm/MSBuild.Sdk.SqlProj#270]
I'm trying to publish a database project that has a password with Comma but I get an issue

```
dotnet publish My.Sql.Database.csproj /p:TargetServerName="SQL_SERVER" /p:TargetDatabaseName="SQL_DATABASE" /p:TargetUser="SQL_USER" /p:TargetPassword="somePassword,WithComma"
```

Error:
```
MSBUILD : error MSB1006: Property is not valid.
Switch: WithComma

For switch syntax, type "MSBuild -help"
```

tried with and without simple quotes, double quotes but nothing worked

**Comment by ErikEJ** [comment]
Try escaping: https://github.com/cake-build/cake/issues/1625#issue-232802421

**Comment by lvitti** [comment]
@ErikEJ Thanks, works replacing the Comma with the hexa value like this:

```
/p:TargetPassword="somePassword%2cWithComma"
```
