### ISSUE TITLE
Publish on web project does not copy the dacpac file

### ISSUE THREAD

**Issue by NWessel** [rr-wfm/MSBuild.Sdk.SqlProj#271]
This might be a configuration issue, but i have tried everything i can and been to every corner of the world wide web.

I have followed this from the .md
![image](https://user-images.githubusercontent.com/9061380/157719044-32d64ffc-2b74-4daf-bcb8-5c2d3037b94b.png)

This is what it looks like in my Web project. The *.Database.Build project is the relevant one.
![image](https://user-images.githubusercontent.com/9061380/157719505-7ed036f4-5f4e-4c71-a605-33246a109368.png)

So what happens is when publishing, is that the file is not there in the publish folder. But interestingly enough, when just building the project, it does get into the bin folder. For some reason they there is a miss alignment :(

![image](https://user-images.githubusercontent.com/9061380/157719825-0a39eb18-d320-49fe-b793-98c680057c4b.png)

![image](https://user-images.githubusercontent.com/9061380/157720006-c18d20bd-b7e0-46be-8a1f-edbdd88cd1da.png)

Any help would be appreciated !

**Comment by NWessel** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>disable</Nullable>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
		<IsPackable>false</IsPackable>
		<SpaRoot>ClientApp\</SpaRoot>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>1701;1702;TS1005;</NoWarn>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>1701;1702;TS1005;</NoWarn>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="6.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.1" />
		<PackageReference Include="Microsoft.Identity.Web" Version="1.22.1" />
		<PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.22.1" />
		<PackageReference Include="Microsoft.SqlServer.DacFx" Version="160.5400.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
	</ItemGroup>

	<ItemGroup>
		
		<Content Remove="$(SpaRoot)**" />
		<None Remove="$(SpaRoot)**" />
		<None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
	</ItemGroup>

	<ItemGroup>
		<Script Include="**" />
		<Script Remove="**.d.ts" />
	</ItemGroup>

	<ItemGroup>
		<Script Remove="Migration\DacpacService.cs" />
	</ItemGroup>


	<ItemGroup>
		<Folder Include="Authentication\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PM.WhatIf.Database.Build\PM.WhatIf.Database.Build.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\PM.WhatIf.Services\PM.WhatIf.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Seeding\GanttTasks.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
		
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

		
		<ItemGroup>
			<DistFiles Include="$(SpaRoot)build\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
				<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>

</Project>

**Comment by ErikEJ** [comment]
Why do you need a reference? just publish the dacpac .csproj to the desired output folder in your pipeline.

**Comment by NWessel** [comment]
Hi Erik, i would normally do that. But we do not have control over the clients web app that will host the solution for themselves (Can be many different customers), so we are "integrating" the dacpac file into the web project and then applying it on the startup if certain conditions are met.

We would also like to have this in our development process so we can actually debug that everything is running as expected.

If there is no solution then we will settle for just doing it in a step in the devops pipeline.
But we would like the pipeline to be as close to the dev process as possible.

Could be we should chat at some point, i unfortunately missed the day where you talked with some of the Projectum Devs :)
Br Nicklas

**Comment by ErikEJ** [comment]
You could add a post build step for local dev?

**Comment by NWessel** [comment]
Yes probably, but it seems wierd since it works with the build part, and not with publish

**Comment by NWessel** [comment]
I managed to fix it ^^
So I added two more properties to anyone that might find this one day :)
Thanks for the help

![image](https://user-images.githubusercontent.com/9061380/157746568-1ec44bba-52ca-436d-a163-7b2b095c5d2c.png)

**Comment by ErikEJ** [comment]
Please share code rather than screenshot.

**Comment by NWessel** [comment]
There we go :)
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>disable</Nullable>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
		<IsPackable>false</IsPackable>
		<SpaRoot>ClientApp\</SpaRoot>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>1701;1702;TS1005;</NoWarn>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>1701;1702;TS1005;</NoWarn>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="6.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.1" />
		<PackageReference Include="Microsoft.Identity.Web" Version="1.22.1" />
		<PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="1.22.1" />
		<PackageReference Include="Microsoft.SqlServer.DacFx" Version="160.5400.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
	</ItemGroup>

	<ItemGroup>
		
		<Content Remove="$(SpaRoot)**" />
		<None Remove="$(SpaRoot)**" />
		<None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
	</ItemGroup>

	<ItemGroup>
		<Script Include="**" />
		<Script Remove="**.d.ts" />
	</ItemGroup>

	<ItemGroup>
		<Script Remove="Migration\DacpacService.cs" />
	</ItemGroup>


	<ItemGroup>
		<Folder Include="Authentication\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PM.WhatIf.Database.Build\PM.WhatIf.Database.Build.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<OutputItemType>Content</OutputItemType>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</ProjectReference>
		<ProjectReference Include="..\PM.WhatIf.Services\PM.WhatIf.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Seeding\GanttTasks.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
		
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

		
		<ItemGroup>
			<DistFiles Include="$(SpaRoot)build\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
				<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>

</Project>
