### ISSUE TITLE
Support for .Net 6.0?? [ETA]

### ISSUE THREAD

**Issue by dcorbin-wintellect** [rr-wfm/MSBuild.Sdk.SqlProj#275]
Are there any estimates (or can it at least be confirmed that this is planned)?

**Comment by jmezach** [comment]
@dcorbin-wintellect We're supporting .NET 6 starting with version 2.0.0 of MSBuild.Sdk.SqlProj.

**Comment by OzBob** [comment]
note to others searching on how to upgrade from old .net 5 sqlproj

update .csproj from:

```
<Project Sdk="MSBuild.Sdk.SqlProj/1.7.0">
```

to

```
<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0">
```
