### ISSUE TITLE
Automatic Nuspec generation

### ISSUE THREAD

**Issue by mwwhited** [rr-wfm/MSBuild.Sdk.SqlProj#283]
https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/d80ce593feb255471cf4b60e46a520e67b52bedb/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L29

The reason a `.nuspec` file needs to be created manually to get `dotnet pack` to work is the fact you are setting the `<NuspecFile>$(MSBuildProjectName).nuspec</NuspecFile>` property.  If you either remove this line or add a condition to check for the existence of the file `dotnet pack` will correctly generate the `.nuspec` for you.  

A simple work around until this project is updated is to just clear out `<NuspecFile></NuspecFile>` in one of your project file's property groups.

**Comment by ErikEJ** [comment]
@mwwhited @jmezach The related PR was closed - and seemed to add other things unrelated to this proposal. Would a targeted PR that just addressed this be an option?

**Comment by jmezach** [comment]
Just adding the condition for existence on the `<NuspecFile>` element would be fine with me.
