### ISSUE TITLE
Could not read schema model header information from package. Collation 1033 is not supported

### ISSUE THREAD

**Issue by ToolMaker** [rr-wfm/MSBuild.Sdk.SqlProj#300]
Hi,

I seem to get a error because of the collation being hardcoded in the model.xml. Is it possible to make this configurable so I can point to some a linux version or just make the error go away :)

What I'm doing, I have posted below. I didnt think this was a MSBuild.SDK.SqlProj issue until it struck me that it is because of the language attribute being not configurable in the schema. PLEASE HELP!

I'm deploying the dacpac from a ubunto docker image.

[Stackoverflow ticket](https://stackoverflow.com/questions/72361873/sqlpackage-error-could-not-read-schema-model-header-information-from-package-co)

**Comment by ErikEJ** [comment]
Looks like this was solved on StackOverflow
