### ISSUE TITLE
Extend or Override

### ISSUE THREAD

**Issue by airwedge1** [rr-wfm/MSBuild.Sdk.SqlProj#324]
It would be nice if there was a feature to for example extend a table that is referenced in another Project.

Say I have table FooBar in Project1 with Id and Name.

In Project2 I am referencing Project1 and the FooBar table, but in Project2 I want to now add an additional column Comment.

Likewise if I have a stored procedure "MyProc" in Project1, but then in project 2 I want to change it.  I want to override the definition from Project1 with the definition that is in Project2.

I could somewhat do this by not not using project references and instead do <Content references, but in the case of the table example if a new column is added in Project1 I want to know about that and now also add to the definition in Project2.  Of course column name conflicts would result in errors.

**Comment by jmezach** [comment]
@airwedge1 Correct me if I'm wrong, but I don't think this is something that was supported in the original `.sqlproj` format. In fact, I don't think this can be done in `.dacpac` either, so that would make it really hard to implement something like this in the scope of this project.

**Comment by airwedge1** [comment]
That is correct.  It is definitely not in the original .sqlproj  I accept that position.
