### ISSUE TITLE
Error observed while installing MSBuild.Sdk.SqlProj.Templates

### ISSUE THREAD

**Issue by Shweta234** [rr-wfm/MSBuild.Sdk.SqlProj#344]
Got below error while installing for the template:
**MSBuild.Sdk.SqlProj.Templates could not be installed, no NuGet feeds are configured or they are invalid**

And same kind of issue is again observed while running the azure pipeline: 
**Unable to find package MSbuild.Sdk.SqlProj. No packages exist with this id in source(s)**

Could you please suggest the solution for it.

**Comment by jmezach** [comment]
@Shweta234 That first error sounds like a configuration issue for NuGet where you have some feeds configured that could not be accessed. Could you share the full output of the `dotnet new --install` command?

The second error seems to refer to a different package, but it again seems to be a configuration issue as it seems no sources are being listed. Or is that just missing here?

**Comment by ErikEJ** [comment]
Closing as the additional info was never supplied
