### ISSUE TITLE
Announcement: Transfer of ownership

### ISSUE THREAD

**Issue by jmezach** [rr-wfm/MSBuild.Sdk.SqlProj#35]
This is not really an issue, but more of an announcement to let everybody know that Im considering transferring the ownership of this repository to my employers [GitHub Organization](https://github.com/rr-wfm/). There are a couple of reasons for that:

1. We are actively using this package in our own projects. In fact I originally set out to build it just for us, but I figured that it could be useful for other people too so I decided to open source it. At the time my employers GitHub Organization didn't even exist yet, so I put it up on my own account.
2. We are looking for ways to contribute back to the community and we feel that this is a good candidate for that. Obviously we are taking the first steps in the open source world here but I really believe we have something to offer here.
3. Provide some form of continuity for the project in case I'm no longer around (for whatever reason) which should hopefully increase possible use of this package as well.

Of course the transfer of ownership is going to change somethings, but I'm confident that a lot will stay the same. We won't be changing the license for example and we would like @ErikEJ to stay on as an outside contributor to this project. For security reasons we are requiring two-factor authentication on the GitHub Organization which is a no-brainer IMHO. We will be adding a code of conduct (based on the [Contributor Covenant](https://www.contributor-covenant.org/)) and a contribution guide as well.

I'm planning to do the transfer sometime next week, unless of course someone is going to comment on this issue saying I'm making a huge mistake. This is both exciting and a little scary to be honest, but I'm confident that this will help push this project forward. If anybody does have concerns about this, don't hesitate to comment on this issue. I'll leave this open until the move has actually happened.

**Comment by ErikEJ** [comment]
Makes sense!

**Comment by jmezach** [comment]
Yeah, I think it makes sense too. I just want to be as open and transparent about this as possible. To be clear, this is not about my employer trying to take control of this project. It is more about supporting this project to bring it further.

**Comment by jmezach** [comment]
I have just completed the ownership transfer. I've added a code of conduct and I've also added our NuGet organization as an owner of the NuGet package.

**Comment by MarkIannucci** [comment]
@jmezach @ErikEJ , this seems like a natural outgrowth for this project, which I think became viable for us at Denver Health in version 1.1.  You may recognize me from #2.  I wanted to let you know that we will likely be incorporating version 1.3 into our deployment and maintenance processes for some of our databases this week.  We look forward to contributing to this project where we can.  Thank you for your work on this thus far.

**Comment by jmezach** [comment]
@MarkIannucci Thank you for using it and supporting us. If you run into any problems, please don't hesitate to file an issue. We'd be happy to help you out.
