### ISSUE TITLE
Unloading project hangs on Visual Studio 2022 v17.3.6

### ISSUE THREAD

**Issue by Thorium** [rr-wfm/MSBuild.Sdk.SqlProj#352]
I have a solution having a few projects.
One of them is MSBuild.Sdk.SqlProj v2.0.0
When I try to close Visual Studio, it always hangs to "Unloading database project".
The VS freezes and almost all the system, I have to always kill it from task manager.

**Comment by jmezach** [comment]
Hmm, that's interesting. Does the same thing happen when you just unload the project and not close Visual Studio? To be honest, this will probably be hard to diagnose as we don't know exactly what happens when VS closes.

**Comment by Thorium** [comment]
Even though it says "Unloading database project" in the VS dialog, this is actually not a problem of the database project.
I attached another VS as a debugger to the hung VS instance, and found out that there was a file-system-lock going on, that wasn't related to database project.

**Comment by jmezach** [comment]
@Thorium Thanks for the feedback!
