### ISSUE TITLE
VS 2022 v.17.4.0 causes "The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0"

### ISSUE THREAD

**Issue by Fulvio75** [rr-wfm/MSBuild.Sdk.SqlProj#353]
Hi, I recently updated Visual Studio 2022 from 17.3.6 version to 17.4.0 version.
After the update, I started to receive this build error locally on a MSBuild.Sdk.SqlProj project, version 2.0.0:

**The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json _**

I've also noticed that my installed SDKs have changed: after VS update they are
`C:\Users\XXXXXX>dotnet --list-sdks`
`2.1.524 [C:\Program Files\dotnet\sdk]`
`3.1.422 [C:\Program Files\dotnet\sdk]`
`7.0.100 [C:\Program Files\dotnet\sdk]`

Previously (1 month ago, when I was able to build the project on my VS 2022) they were
`C:\Users\XXXXXX>dotnet --list-sdks`
`2.1.524 [C:\Program Files\dotnet\sdk]`
`3.1.422 [C:\Program Files\dotnet\sdk]`
`6.0.402 [C:\Program Files\dotnet\sdk]`

I rollbacked VS update (returning to 17.3.6 version) and I observed that:
1. The SDK was rollbacked too from 7.0.100 to 6.0.402
2. My MSBuild.Sdk.SqlProj now builds again.

I think a new version of MSBuild.Sdk.SqlProj is necessary to support VS 2022 v.17.4.0 and newer versions of Microsoft IDE.

**Comment by ErikEJ** [comment]
Why would VS remove a LTS SDK?

**Comment by Condor2708** [comment]
I have workaround with previous versions -> migrating from net5 to net6
changing the csproj adding 		<BundledNETCoreAppTargetFrameworkVersion>5.0</BundledNETCoreAppTargetFrameworkVersion>

I think you can use 
<BundledNETCoreAppTargetFrameworkVersion>6.0</BundledNETCoreAppTargetFrameworkVersion>
until a new version of the dacpactool is deployed that supports net7

**Comment by DanielLoth** [comment]
Hi,

I've experienced the same with the new VS2022 version. I still have at least some .NET 6 versions installed though:

```
PS C:\Users\daniel.loth> dotnet --list-sdks
2.1.602 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
3.1.425 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.306 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
```

I've attempted to use `global.json` to control which SDK version performs the build. However Visual Studio seems to be ignoring the configuration in this file:

```
{
    "sdk": {
        "version": "6.0.306",
        "rollForward": "disable",
        "allowPrerelease": false
    }
}
```

On the other hand, once I add this `global.json` configuration I can successfully build via `dotnet build` on the command line.

Output when building via `dotnet build` on the command line **before** using `global.json`:
```
PS C:\...\MyDbProj> dotnet build
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored C:\...\MyDbProj.csproj (in 221 ms).
C:\Users\daniel.loth\.nuget\packages\msbuild.sdk.sqlproj\2.0.0\Sdk\Sdk.targets(98,5): error : The current SDK bundles t
arget framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1,
5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs
 installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json [C:\...\MyDbProj.csproj]

Build FAILED.

C:\Users\daniel.loth\.nuget\packages\msbuild.sdk.sqlproj\2.0.0\Sdk\Sdk.targets(98,5): error : The current SDK bundles t
arget framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1,
5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs
 installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json [C:\...\MyDbProj.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.50
```

Output when building via `dotnet build` on the command line **after** adding `global.json`:
```
PS C:\...\MyDbProj> dotnet build
Microsoft (R) Build Engine version 17.2.2+038f9bae9 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\...\MyDbProj.csproj (in 348 ms).
  Using target framework net6.0 to run DacpacTool
  Using package name MyDbProj and version 1.0.0.0
  Using SQL Server version Sql130
  Adding C:\...\SomeFile1.sql to the model
  Adding C:\...\SomeFile2.sql to the model
  Writing model to C:\...\obj\Debug\netstandard2.0\MyDbProj.dacpac
  Adding C:\...\Script.PreDeployment.sql to package
  Adding C:\...\Script.PostDeployment.sql to package
  MyDbProj.Build -> C:\...\bin\Debug\netstandard2.0\MyDbProj.dacpac
  Successfully created package 'C:\...\bin\Debug\MyDbProj.1.0.0.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.18
```

**Comment by ErikEJ** [comment]
@jmezach I will do a PR to fix this, got hit by it myslef now 😄

**Comment by DanielLoth** [comment]
> Kinda weird though that VS suddenly uses .NET 7 by default instead of looking at the global.json. That's not how it is supposed to work afaik.

That's what I thought. 😄 I'm glad it's not just me. Peculiar though, right?

**Comment by herao67** [comment]
> <BundledNETCoreAppTargetFrameworkVersion>6.0</BundledNETCoreAppTargetFrameworkVersion>

This worked for me.

**Comment by Ryanman** [comment]
For anyone late to the party here, I'd warn you against using:

`<BundledNETCoreAppTargetFrameworkVersion>6.0</BundledNETCoreAppTargetFrameworkVersion>`

This will work for a local build in VS, but break in (for instance) an Azure DevOps Pipeline. Using the `global.json` file at the root and ensuring your pipeline does too is a more cohesive fix.

**Comment by DanielLoth** [comment]
Hi @ErikEJ, @jmezach,

I'm a bit late writing this, but I just wanted to circle back and thank you both for putting out a fix so quickly.

**Comment by ErikEJ** [comment]
@Ryanman Just use version 2.2.0

**Comment by Ryanman** [comment]
@ErikEJ I still had issues with this locally. My solution is a bit strange though (I've got a standard project and a 4.8 project in it....) which may be why I needed it. 

Or it's because I installed VS22 just a couple days ago and am still figuring out what's changed since 19 - in any case that's what I needed even with 2.2.0
