### ISSUE TITLE
PackageReferences don't resolve wildcard versions

### ISSUE THREAD

**Issue by jeffrosenberg** [rr-wfm/MSBuild.Sdk.SqlProj#36]
When using the `<PackageReference>` element to build a composite database project, the referenced version should support the use of "floating versions", i.e. wildcards, per the [documentation here](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#floating-versions). When using this SDK (and adding a few debugging messages to see what's going on behind the scenes), it appears that it is not resolving the wildcard to the most recent version, but just using the wildcard literally. 

The following is a simplified example of two .csproj files I'm building into a composite database:

### Base.csproj ###
``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.1.1">

  <!-- Database configuration properties -->
  <PropertyGroup>
    <!-- ... -->
  </PropertyGroup>

  <!-- File includes / excludes -->
  <!-- MSBuild.Sdk.SqlProj Sdk defaults to including all *.sql files -->
  <ItemGroup>
    <Content Remove="target/**/*.sql" />
  </ItemGroup>
```

### Plus.csproj ###
``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.1.1">

  <!-- Database configuration properties -->
  <PropertyGroup>
    <!-- ... -->
  </PropertyGroup>

  <!-- File includes / excludes -->
  <!-- MSBuild.Sdk.SqlProj Sdk defaults to including all *.sql files -->
  <ItemGroup>
    <Content Remove="Scripts/**/*.sql" />
    <Content Remove="target/**/*.sql" />
    <PostDeploy Include="Scripts/Script.PostDeployment.sql" />
    <PreDeploy Include="Scripts/Script.PreDeployment.sql" />
  </ItemGroup>
  <!-- References to dacpac dependencies -->
  <ItemGroup>
    <PackageReference Include="Base" Version="7.6.*" />
  </ItemGroup>
</Project>
```

When I try to build the "Plus" package, I see the following messages from Sdk.targets:

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  PackageReference.Identity is Base
  Resolved dacpac file from package Base to /users/jrosenberg/.nuget/packages/base/7.6.*/tools/Base.dacpac
  Resolved database package references: 
```

Interestingly, if I change the dependency version to 7.7.*, MSBuild stops me before even calling this SDK, so MSBuild and NuGet appear to be resolving the dependency version.  

```
~/Plus/Plus.csproj : error NU1102: Unable to find package Base with version (>= 7.7.0)
~/Plus/Plus.csproj : error NU1102:   - Found 4 version(s) in local [ Nearest version: 7.6.0 ]
~/Plus/Plus.csproj : error NU1102:   - Found 0 version(s) in nuget.org
```

I would guess that there must be some way to get the actual resolved dependency version from MSBuild/NuGet, above and beyond `%(PackageReference.Version)`, which appears to return the literal contents of that attribute. I'm trying to do some research into this, but so far I haven't been able to figure out how that's done, so thought I would log this issue in the hopes that one of the maintainers understands this better than I do. 😄 

NOTE: The ability to use wildcards for _pre-release_ versions [appears to be new](https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions), but for _released_ versions it has been a part of MSBuild for quite a while.

**Comment by jmezach** [comment]
This is interesting, thanks for reporting this. Currently we're using the version from the `PackageReference` directly to resolve the physical location on disk. I'm guessing MSBuild attaches some metadata to the `PackageReference` with the actually resolved version. Would you mind running `dotnet build /bl` from the command line on your project and share the resulting `msbuild.binlog` file somewhere? That would give me some insights into how it works under the hood.

**Comment by jeffrosenberg** [comment]
Out of an abundance of caution, I think I'd better check with some folks in my organization to make sure that's okay. I'll get something shared as soon as I can, but may take me a while.

**Comment by jmezach** [comment]
Sure, I get it. I'm not sure what exactly gets logged in a binary log to be honest. I guess it is everything you pass into MSBuild somehow. I guess there could be secrets in there somewhere, especially if you pass some on the command line to make your build succeed.

If you really don't want to share, I guess a simple repo project would do as well.

**Comment by jeffrosenberg** [comment]
I put together a simple repo to keep things easy. As it turns out MSBuild logs a lot -- including all of your environment variables! 😄 

Github didn't like me attaching the binlog file, so it's attached as a zip. I finally got myself set up with a binlog viewer on a Windows VM, so I'll try to take a look myself as well.
[msbuild.binlog.zip](https://github.com/jmezach/MSBuild.Sdk.SqlProj/files/5085327/msbuild.binlog.zip)

**Comment by jeffrosenberg** [comment]
I noticed something while looking through the first binary log -- the only property that appeared to have the version string I wanted (7.6.0) was named `PkgBase`, which I noticed had a related name to my package "Base". Because "Base" is a name you see in a lot of properties, I updated my repo to include a second dependency named "Second". Sure enough, there's also a `PkgSecond` now with the proper version string. I'm attaching a second binlog that includes that second dependency.

[plus.binlog.zip](https://github.com/jmezach/MSBuild.Sdk.SqlProj/files/5085414/plus.binlog.zip)

**Comment by jmezach** [comment]
I'm aware of the `Pkg<package-id>`properties being set by MSBuild. In fact we were [originally using that](https://github.com/jmezach/MSBuild.Sdk.SqlProj/commit/5f2212019c12084d77e1a6f0d1ffad37c934678d#diff-aa39a3574d38e789f91cd32cdb7dfed4) to resolve the physical location of the package. I can't remember exactly why I changed it to resolving the path manually, but I believe it had something to do with the fact that the `Pkg<package-id>` property isn't always being generated as you would expect.

Perhaps we should change it back to what we had originally and then have a fallback in case the `Pkg<package-id>` property isn't available. Or we need to figure out when MSBuild generates the property and when it does not and then base the physical location on that. So far I haven't found any documentation on that though.

By the way, there's also an [online MSBuild binary log viewer](https://live.msbuildlog.com) now that you can use if you're not on Windows.

**Comment by jmezach** [comment]
I just did some research and according to [this](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty) you can either have MSBuild explicitly generate that property, or it will automatically generate it if the package has a `tools` folder. Since we're packaging `.dacpac`'s into the `tools` folder when you use this SDK I guess we can rely on the `Pkg<package-id>` property to be available. However that will increase the minimum requirements for using this package, since it seems that the property is only being generated starting with VS 2019 (16.0) so you can use it only if you have a .NET Core SDK installed that supports that version of Visual Studio. So I still think that having a fallback in case the property doesn't exist makes sense.

**Comment by jmezach** [comment]
@jeffrosenberg Do you think you can sent a PR for this? If not, that's fine, but I don't think I'll have much time this week to look into this.

**Comment by jeffrosenberg** [comment]
I can give it a shot! I'm still not quite sure how to handle this sort of dynamically-named variable, but if you say you were using something similar than I can just look back into the project history. I'll give it a try this week. If I can't figure it out, it can certainly wait until you have time to look at it, but I'll do my best to resolve it myself.

**Comment by jmezach** [comment]
@jeffrosenberg Version 1.3.0 is now up on NuGet which includes the fix for this issue. Thanks again for your contribution.
