### ISSUE TITLE
How to specify Database properties like 

### ISSUE THREAD

**Issue by OzBob** [rr-wfm/MSBuild.Sdk.SqlProj#360]
In the older framework SQLproj style project there was a right click project | Project Settings | Database settings dialog 

![image](https://user-images.githubusercontent.com/1796771/202349911-7b76f0e4-d77b-4e63-81ab-0c5f0f444139.png)

That allowed the database level settings to be turned on/off, e.g.

- QUOTED_IDENTIFIER
- ANSI_NULLS
- etc

How to specify these as ON in the newer MSBuild.Sdk.SqlProj format?

**Comment by jeffrosenberg** [comment]
Hi @OzBob, you can set Model Properties on your project file; please see [this documentation](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#model-properties). A list of available options is available from Microsoft [here](https://docs.microsoft.com/dotnet/api/microsoft.sqlserver.dac.model.tsqlmodeloptions).

**Comment by OzBob** [comment]
@jeffrosenberg thx
did you mean '[model-compiler-options](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#model-compiler-options)' ? 

so if i add a 

```
<AnsiNullsOn>True</AnsiNullsOn>
```

that should work?

**Comment by ErikEJ** [comment]
It is Model properties on the docs, but yes
