### ISSUE TITLE
The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0

### ISSUE THREAD

**Issue by krishnan-thirumalai** [rr-wfm/MSBuild.Sdk.SqlProj#371]
Hello, 
I couldn't build the project due to below error

**Build Error**

Severity	Code	Description	Project	File	Line	Suppression State
Error		The current SDK bundles target framework '7.0' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json	LLamasoft.Tableau.Integration.Tests.Database	C:\Users\Krishnan Thirumalai\.nuget\packages\msbuild.sdk.sqlproj\2.0.0\Sdk\Sdk.targets		

**My Project file** 

```xml
<Project Sdk="MsBuild.Sdk.SqlProj/2.0.0">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <SqlServerVersion>Sql140</SqlServerVersion>
        <!-- For additional properties that can be set here, please refer to https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#model-properties -->
    </PropertyGroup>

    <PropertyGroup>
        <!-- Refer to https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#publishing-support for supported publishing options -->
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\sourece\test1.sql" Link="test1.sql" />
        <Content Include="..\sourece\test2.sql" Link="test2.sql" />
        <Content Include="..\sourece\test3.sql" Link="test3.sql"" />
    </ItemGroup>
</Project>

```

**Error Source**

` 
  <Target Name="ValidateEnvironment">
    <PropertyGroup>
      <DacpacToolTfm Condition="'$(BundledNETCoreAppTargetFrameworkVersion)' == '3.1'">netcoreapp$(BundledNETCoreAppTargetFrameworkVersion)</DacpacToolTfm>
      <DacpacToolTfm Condition="'$(BundledNETCoreAppTargetFrameworkVersion)' != '3.1'">net$(BundledNETCoreAppTargetFrameworkVersion)</DacpacToolTfm>
      <DacpacToolExe>$(MSBuildThisFileDirectory)../tools/$(DacpacToolTfm)/DacpacTool.dll</DacpacToolExe>
    </PropertyGroup>
    <Error Condition="!Exists($(DacpacToolExe))"
           Text="The current SDK bundles target framework '$(BundledNETCoreAppTargetFrameworkVersion)' which is not supported by MSBuild.Sdk.SqlProj. Either install a .NET Core SDK that supports 3.1, 5.0 or 6.0, or file an issue at https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/ to add support. If you have preview SDKs installed, you may have to use a global.json file: https://docs.microsoft.com/dotnet/core/tools/global-json" />
    <Message Importance="High" Text="Using target framework $(DacpacToolTfm) to run DacpacTool" />
  </Target>
`

Other Information
==============

**_installed sdks_**
![image](https://user-images.githubusercontent.com/77965767/204298117-bc8e6910-9560-4adb-8e7c-b58ca71bf4d7.png)

_**installed runtime**_
![image](https://user-images.githubusercontent.com/77965767/204298364-4c897244-02f2-4bb2-a80b-8810cace1b13.png)

IDE : Visual Studio 2022.

**Comment by jeffrosenberg** [comment]
We just released a new version that resolves this, please make sure you're using our latest and that should fix the issue!

**Comment by ErikEJ** [comment]
Update your SDK:

    <Project Sdk="MsBuild.Sdk.SqlProj/2.3.0">

**Comment by mskichu** [comment]
Thank you sorted now

**Comment by jmezach** [comment]
Looks like this has been resolved. Closing.
