### ISSUE TITLE
Add support for ProjectReference

### ISSUE THREAD

**Issue by jmezach** [rr-wfm/MSBuild.Sdk.SqlProj#40]
While MSBuild.Sdk.SqlProj supports `PackageReference` for referencing NuGet packages and automatically include their embedded `.dacpac`'s as part of the build we do not currently support `ProjectReference`. In a `.sqlproj` this is typically defined as:

```xml
<ProjectReference Include="..\Database1\Database1.sqlproj">
  <Name>Database1</Name>
  <Project>{b4a1acc8-f726-499e-a0d5-955e146dc10a}</Project>
  <Private>True</Private>
  <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
  <DatabaseSqlCmdVariable>Database1</DatabaseSqlCmdVariable>
</ProjectReference>
```

In the case of SDK-style projects we can probably get rid of the `Project` metadata since those GUID's aren't used anymore. I'm not entirely sure what the `Name` and `DatabaseSqlCmdVariable` metadata is used for though. The `Private` metadata probably controls whether the `.dacpac` of the project being referenced is being copied to the output folder of the project that has the reference, which shouldn't be too hard to implement. The `SuppressMissingDependenciesErrors` might be a little bit more tricky and will require some research.

We'll also need to resolve the path of the `.dacpac` for the referenced project. I'm hoping that we can already get that from MSBuild somehow since it supports project to project references already.

**Comment by mgrosperrin** [comment]
Hello,
for information, the `DatabaseSqlCmdVariable` defines the name of the variable you can use in your scripts to reference the database/project.
