### ISSUE TITLE
Add support for incremental builds

### ISSUE THREAD

**Issue by ChristopherHaws** [rr-wfm/MSBuild.Sdk.SqlProj#400]
When I build my project, I get the following warning in the build output:
```
WARNING: Potential build performance issue in 'DatabaseProject.csproj'.
The project does not appear up-to-date after a successful build:
Input 'C:\dev\redacted\src\DatabaseProject\obj\DatabaseProject.csproj.nuget.g.props'is newer (2023-02-24 6:15:48 AM) than earliest
output 'C:\dev\redacted\src\DatabaseProject\bin\Debug\netstandard2.0\DatabaseProject.dacpac' (2023-02-09 7:01:46 AM), not up-to-date.
See https://aka.ms/incremental-build-failure.
```

https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md

**Comment by jmezach** [comment]
@ChristopherHaws Thanks for reporting this. We've had a few similar issues, such as #63. I remember looking at the up-to-date document back then, but couldn't figure out why it wouldn't work at the time as we didn't have too much to go on.

This output helps, although it is interesting to see such a huge time difference between those two files. Can you consistently reproduce this? If so, it would be really helpful to have a binary log of both the initial build and the incremental build.

**Comment by zlatanov** [comment]
I was able to achieve this by adding the following to the csproj file:

```xml
<ItemGroup>
        <UpToDateCheckInput Include="**/*.sql" />
</ItemGroup>
```

**Comment by ErikEJ** [comment]
@ChristopherHaws Did you try @zlatanov suggestion above?

**Comment by asbjornb** [comment]
Just to add info that might or might not help. I do something similar to what @zlatanov suggests but referring to the files in the original project with the UpToDateCheckInput like this:
`<Project Sdk="MSBuild.Sdk.SqlProj/2.5.0">
  <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>
      <SqlServerVersion>Sql140</SqlServerVersion>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <DeployOnPublish>false</DeployOnPublish>
      <OutputPath>bin</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <UpToDateCheckInput Include="../MyAppDatabase/**/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../MyAppDatabase/**/*.sql" />
    <Content Remove="../MyAppDatabase/bin/**" />
    <Content Remove="../MyAppDatabase/obj/**" />
    <Content Remove="../MyAppDatabase/Deployment/**" />
    <Content Remove="../MyAppDatabase/Security/Users/**" />
  </ItemGroup>
</Project>
`

I've fiddled a bit with different options but got this to work. On the other end referring to the MSBuild.Sdk.SqlProj/2.5.0-project from other projects without explicitly linking the dacpac seems to also require an UpToDateCheck on the referring projects like this:
`  <ItemGroup>
    <UpToDateCheckBuilt Include="$(OutDir)MyAppDatabase.Build.dacpac" Original="../MyAppDatabase.Build/bin/MyAppDatabase.Build.dacpac" />
  </ItemGroup>`

**Comment by ErikEJ** [comment]
@ChristopherHaws any news?

**Comment by ErikEJ** [comment]
@ChristopherHaws I am closing this now due to no response
