### ISSUE TITLE
Question: Error SQL72033 when using sqlpackage /Action: Script

### ISSUE THREAD

**Issue by dbatlas** [rr-wfm/MSBuild.Sdk.SqlProj#403]
I don't know if this is a possible bug or just user error on my part, this is my first time building a db solution with this SDK project - which is very cool btw so thanks for making it.

I created my buddy project and was able to build my db locally without any warnings or errors after adding the reference to master dacpac as so
```
<Project Sdk="MSBuild.Sdk.SqlProj/2.5.0">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <SqlServerVersion>SqlAzure</SqlServerVersion>
		<!--SuppressTSqlWarnings>71502</SuppressTSqlWarnings -->
		<TreatTSqlWarningsAsErrors>True</TreatTSqlWarningsAsErrors>
        <!-- For additional properties that can be set here, please refer to https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#model-properties -->
    </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SqlServer.Dacpacs.Azure" Version="160.0.0" DacpacName="master" />
		<Content Include="..\iot_masterdb\**\**\*.sql" />
	</ItemGroup>
</Project>
```

I was then able to use dotnetcorecli build task on ubuntu-latest build agent to build the dacpac via Azure DevOps, now is where I am encountering the error when I am trying to execute sqlpackage to generate a SQL script

```
	sqlpackage `
		/Action:Script `
		/sourcefile:"/home/vsts/work/1/s/Master.Build/bin/release/netstandard2.0/Master.Build.dacpac" `
		/ReferencePaths:"/home/vsts/work/1/s/Master.Build/bin/release/netstandard2.0/master.dacpac" `
		/TargetServerName:$db_server_name `
		/TargetDatabaseName:$db_name `
		/TargetUser:"$db_user" `
		/TargetPassword:"$DBPassword" `
		/outputpath:"/home/vsts/work/1/s/Master.Build/bin/release/netstandard2.0/IOT_Master_Deploy.sql" 
```

Which results in something like
Error SQL72033: This deployment may encounter errors during execution because [dbo].[AddNewPlant] depends on [sys].[sp_executesql] and [sys].[sp_executesql] does not exist in the target database.
Error SQL72033: This deployment may encounter errors during execution because [dbo].[sp_WhoIsActive] depends on .... blah blah blah

For now I am working around this using
/p:TreatVerificationErrorsAsWarnings='True'

But wondering again if I hit bug or if I am doing something wrong - thanks!

**Comment by ErikEJ** [comment]
@dbatlas Same version of sqlpackage on both agent types?

**Comment by jmezach** [comment]
To be honest, this does seem to an issue with sqlpackage. I'm not sure if there's much we can do about it here. Perhaps this is best filed over at https://github.com/Microsoft/dacfx. Feel free to re-open this though if they find out that it has something to do with how the .dacpac is created.
