### ISSUE TITLE
DacpacTool invocation fails on Windows if the maximum command length is exceeded

### ISSUE THREAD

**Issue by jeffrosenberg** [rr-wfm/MSBuild.Sdk.SqlProj#43]
Apparently there's a limit to the length of a command sent at the Windows command line ([8191 characters](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation), possibly up to [32767 in some situations](https://support.thoughtworks.com/hc/en-us/articles/213248526-Getting-around-maximum-command-line-length-is-32767-characters-on-Windows)). Because DacpacTool is called via the command line, and each included file is sent as a separate argument, projects with either (a) a lot of objects or (b) very long paths to each object will eventually exceed this limit and fail.

I ran into this limitation and was able to work around it by creating a symbolic link to shorten my paths, but that's a workaround at best and projects with a large number of objects won't be able to do that. 

One possible solution to the problem would be to pass the list of included objects in a temporary file, rather than via the CLI.

**Comment by jeffrosenberg** [comment]
As mentioned, I've been able to work around this, so it's a low-priority issue for me personally, but I wanted to make sure it got logged so it could be dealt with at some point.

**Comment by jmezach** [comment]
I guess we could write a list of files that are part of the project to a temporary file in the `obj` folder and then read that file from the `DacpacTool`. Shouldn't be too hard to do with the MSBuild built-in `WriteLinesToFile` task. If anyone's willing to sent a PR for this that would be great!

**Comment by jeffrosenberg** [comment]
I'll take care of this at some point. This isn't a really high priority for me, but as you mentioned, it shouldn't be too difficult, so I'll try to get a PR in for it this week or next.

**Comment by jmezach** [comment]
That would be awesome! Really appreciate all the work you've been putting into this.

**Comment by jmezach** [comment]
Version 1.6.1 that contains the fix for this is now up on NuGet.org.
