### ISSUE TITLE
Referencing MSSQL master dacpacs no longer accurate 

### ISSUE THREAD

**Issue by sloncho** [rr-wfm/MSBuild.Sdk.SqlProj#441]
It appears that MS have changed and split the dackpacks in 2 separate projects. Using the current [readme instructions](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#referencing-system-databases) fails to publish.

The old nuget packages are removed: https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs

Using the new one restored the functionality: https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Master

Ref (change): https://github.com/microsoft/DacFx/pull/266

**Comment by jmezach** [comment]
@sloncho Thanks for the heads-up. I think we'll only need to update our docs, but don't need to make any code changes for this. Feel free to send a PR with the updated docs if you're up for it, otherwise I'll do it when I get around to it (which might be a while ;)).

**Comment by sloncho** [comment]
@jmezach I'll do that, but I'm not sure if it is only docs. With the new structure, they place only single dacpac in the tools folder. The current implementation of the sdk still requires the use of `DacpacName="master"` attribute in the project reference, otherwise it does not work. That attribute looks like redundant when there is only one file. Does that need to change?

**Comment by sloncho** [comment]
It appears that I was too fast to report "it is working". It appears that there is a problem using the new nuget package from MS.:

1. If used w/o the "DacpacName" (what I reported "working"):
    - it builds and deploys
    - VS still reports the warnings - meaning id did not get the file, as the name is not specified
2. If DacpacName=master
    -  VS does not report error
    - deploy fails with `EXEC : error : An unknown error occurred while deploying database 'MyDb': Object reference not set to an instance of an object.`

The error happens both with 2.5.0 and 2.6.0 of the sdk, using dotnet sdk 6.0 and 7.0. The nuget package I use is v.150, as this is the server version we use.

This starts to look like a bug (here or in the MS nuget). Unfortunately, I'm not well equipped to debug this. Any pointers?

**Comment by gfody** [comment]
When I attempt to add the Microsoft.SqlServer.Dacpacs.Master via "Manage NuGet Packages..." I get this error in the package manager output:
> Installed Microsoft.SqlServer.Dacpacs.Master 150.0.0 from https://api.nuget.org/v3/index.json with content hash V56gKQNJ9se91yjtFPZsFTcBWYvRlL9FZzgk0XUCR6jiuHTdlcHWXpEmMILvZdVaAzO/zCTNPuyla+N863cNvA==.
Package 'Microsoft.SqlServer.Dacpacs.Master 150.0.0' has a package type 'DACPAC' that is not supported by project 'DBA'.

('DBA' is my MSBuild.Sdk.SqlProj project)

**Comment by jmezach** [comment]
@gfody That's interesting. I guess we'd need to add something to the SDK to indicate that the project supports package references of type `dacpac`. I'd have to do some digging to find out what would be needed to make that work, but it is good to know there is a workaround available.

**Comment by Nathalilly** [comment]
I found that when adding via "manage nuget packages..." it does not set this:
<DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
Had to manually add.

**Comment by ErikEJ** [comment]
@jmezach Is there anything more for us to do here?

**Comment by jmezach** [comment]
I think for now people should just add these packages to their project files as we've described in the docs. Making this work properly in VS through the UI is potentially a lot of work I'm not really looking to take on at this time.

**Comment by Nathalilly** [comment]
> I think for now people should just add these packages to their project files as we've described in the docs. Making this work properly in VS through the UI is potentially a lot of work I'm not really looking to take on at this time.

link for those docs?

**Comment by jmezach** [comment]
See [this section in README](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj?tab=readme-ov-file#referencing-system-databases).
