### ISSUE TITLE
Issue downloading from nuget...

### ISSUE THREAD

**Issue by mickeysox** [rr-wfm/MSBuild.Sdk.SqlProj#443]
Hi All,

I am facing the following issue:

```
The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'MSBuild.Sdk.SqlProj.2.6.0' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.
  Unable to find package 'MSBuild.Sdk.SqlProj.2.6.0'.
```

I have tried downloading the package directly via edge and the hangs at the very end.

Just to confirm, I have tried other packages and they seem to work fine i.e. the .templates file downloads fine.

**Comment by jmezach** [comment]
@mickeysox Interesting. This is the first time I've heard of such an issue. Unfortunately I don't think there is a whole lot we can do about this from our end as this sounds more like an infrastructural issue at the NuGet.org side. Perhaps try it again today (or tomorrow depending on your timezone I guess ;)), it might just be a temporary glitch or something. If the issue persist I think we'll have to get in touch with the NuGet team to figure out what's going wrong here.

**Comment by jmezach** [comment]
@mickeysox I just tried and it downloads just fine. Maybe there is some kind of firewall or proxy in the way that causes the download to fail?

**Comment by mickeysox** [comment]
@jmezach great thank you, must be my side, although strange that it is only specifically this package but all others seem to work fine.  I wonder if it's the size maybe. I'll close this as it's only not working for me, thanks for replying.
