### ISSUE TITLE
Defining SQLCMD variables in the project prevents them from being set via environment variables

### ISSUE THREAD

**Issue by MrazqRuby** [rr-wfm/MSBuild.Sdk.SqlProj#448]
It seems to me that defining the `<SqlCmdVariable> ... </SqlCmdVariable>` is actually worse than not defining it.

I am building a .dacpac with this SDK with a Post-Deploy script that uses variables like this:
```sql
IF (1 = ISNULL($(SQLCMD_DEPLOY_CONFIGS), 0))
BEGIN
# ...
END
```
I am **not** defining  `<SqlCmdVariable> ... </SqlCmdVariable>` anywhere.
1. Running `sqlpackage.exe /a:Publish ...` in a container where the SQLCMD_DEPLOY_CONFIGS environment variable is defined results in the value from the environment variable being replaced in the script.
2. Running `sqlpackage.exe /a:Publish ... /v:SQLCMD_DEPLOY_CONFIGS=0` also works, although it prints _"The following SqlCmd variables are not defined in the target scripts: SQLCMD_DEPLOY_CONFIGS."_

**BUT**

If I go and now define:
```xml
<SqlCmdVariable Include="SQLCMD_DEPLOY_CONFIGS">
		<!--Defines whether configuration scripts should be deployed: 0 - No, 1 - Yes-->
	<DefaultValue>$(SQLCMD_DEPLOY_CONFIGS)</DefaultValue>
	<Value>$(SQLCMD_DEPLOY_CONFIGS)</Value>
</SqlCmdVariable>
```

then the approach with the environment variable (1) **no longer works**. So to me it seems that it is worse to define the sqlcmd vars?

**Comment by ErikEJ** [comment]
@jmezach Wonder if we are treating "DefaultValue" wrong?

`<SqlCmdVariableArguments>@(SqlCmdVariable->'-sc %(Identity)=&quot;%(DefaultValue)&quot;', ' ')</SqlCmdVariableArguments>`

From https://learn.microsoft.com/sql/tools/sql-database-projects/concepts/sqlcmd-variables

"The DefaultValue element is optional. When a default value is provided, it's only used to load in the publish dialog of graphical tools for SQL projects. The default value isn't compiled into the .dacpac file and a command line deployment without the values specified by a publish profile or the /v option to specify values results in empty values for the SQLCMD variables."

**Comment by ErikEJ** [comment]
@jmezach Thoughts?

**Comment by jmezach** [comment]
It appears we are indeed putting the DefaultValue into the resulting `.dacpac`. Not sure what `.sqlproj` does though. We might want to test that.

**Comment by ErikEJ** [comment]
.sqlproj contents:

```xml
  <ItemGroup>
    <SqlCmdVariable Include="Test">
      <DefaultValue>TheDefaultValue</DefaultValue>
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
  </ItemGroup>

```
.dacpac model.xml contents:
```xml
<CustomData Category="SqlCmdVariables" Type="SqlCmdVariable">
<Metadata Name="Test" Value=""/>
</CustomData>
```

**Comment by ErikEJ** [comment]
Yes, incorrectly, I think: (Extensions.cs)

![image](https://github.com/user-attachments/assets/d3d50800-01cc-41a0-8247-7ecbac41a0bc)

**Comment by jmezach** [comment]
I guess we can fix it in the Sdk or in the DacpacTool. Although the blame there in your screenshot seems to suggest we did add this on purpose?

**Comment by jmezach** [comment]
Looks like we added this in https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/368

**Comment by ErikEJ** [comment]
Maybe it got added without knowledge of the link I shared above?

**Comment by jmezach** [comment]
Perhaps. At the very least this would be a breaking change I think. We could consider changing this behaviour in 3.0?

**Comment by ErikEJ** [comment]
@jmezach I think we should, it is not correct behaviour. And fine to break in a major release
