### ISSUE TITLE
Store procedure is not added as part of DACPAC

### ISSUE THREAD

**Issue by eddykuhan** [rr-wfm/MSBuild.Sdk.SqlProj#464]
Version : MSBuild.Sdk.SqlProj/2.6.1

HI , I've noticed that when I add a Store Procedure with syntax "CREATE OR ALTER PROC dbo.Procedure1" its not being published to target db. But, its published when I use "CREATE PROCEDURE dbo.Procedure1" or "CREATE PROC dbo.Procedure1".

1>Using target framework net6.0 to run DacpacTool
1>Using package name Project1.Database and version 1.0.0
1>Setting property RecoveryMode to value Simple
1>Using SQL Server version SqlAzure
1>Adding C:\Projects\xxx\src\ Project1.Database\dbo\Stored Procedures\Procedure1.sql to the model

C:\sqlpackage\sqlpackage.exe /Action:Publish   /TargetConnectionString:"Server=localhost,1433;Initial Catalog=Mydb;Persist Security Info=False;User ID=sa;Password=xxx;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"  /SourceFile:Project1.Database.dacpac    /Properties:IncludeCompositeObjects=True

Any idea what's wrong ?

**Comment by ErikEJ** [comment]
You should always just use "CREATE" - think of the database project as a description of your desired state, not taking previous state ( "OR ALTER" ) into consideration.
