### ISSUE TITLE
EXEC warning SQL73162 --> Option TrustServerCertificate is missing

### ISSUE THREAD

**Issue by lucasrueda** [rr-wfm/MSBuild.Sdk.SqlProj#476]
I run the following:

```bash
dotnet publish ./myproj.csproj \
/p:TargetServerName=10.0.0.1 \
/p:TargetUser=MYUSER \
/p:TargetDatabaseName=MYDATABASE \
/p:Encrypt=False
```

It fails showing:
```
EXEC : warning SQL73162: Changes to connection setting default values were incorporated in a recent release.
More information is available at https://aka.ms/dacfx-connection 
```
The link provided talks about certificates in the connection
![image](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/24287521/e1426535-8656-48c6-ae7d-10d09c0ee905)

When I run the deploy from Visual Studio 2022, it works. The connection string looks like this:

```
Data Source=MYSERVER;Persist Security Info=True;User ID=MYUSER;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False
```
As you can see, the last option is `TrustServerCertificate` set to `False`;

So, `Encrypt=False` seems to be not enough

**Comment by ErikEJ** [comment]
I suggest you just install the global tool Microsoft.Sqlpackage and then use the full fledged sqlpackage command

**Comment by lucasrueda** [comment]
Thanks for your response @ErikEJ 
Just to let you know, the database I was targeting was running SQL Server 2008 R1.

I needed to downgrade the SSL threshold as mentioned here:
[Microsoft.Data.SqlClient.SqlException](https://github.com/dotnet/SqlClient/issues/633)

But even with that change, I couldn't deploy successfully because SqlClient needs SQLServer 2008 R3.. so.. never mind.
