### ISSUE TITLE
Support for linked servers

### ISSUE THREAD

**Issue by marcadella** [rr-wfm/MSBuild.Sdk.SqlProj#482]
I get a lot of unresolved references to resources living on a linked server. Is there a way to define the linked server in the project? Or is there a way to somehow ignore such errors?

**Comment by ErikEJ** [comment]
Please share the exact errors you get

**Comment by marcadella** [comment]
Given the sql: `... from LBR_ROLLE P join [ILPROD2]..[LBR].[LBR_ROLLE] L on L.id = P.id`, I get: "error SQL71501: SqlView: [dbo].[vPROD_LBR_ROLLE_DIFF] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[LBR_ROLLE].[L]::[ID], [ILPROD2].[].[LBR].[LBR_ROLLE].[ID] or [ILPROD2].[].[LBR].[LBR_ROLLE].[L]::[ID]."
I don't really see why `[ILPROD2]..[LBR].[LBR_ROLLE]` is ambiguous and it looks like the model doesn't know how to handle `ILPROD2` which is a linked server.

**Comment by ErikEJ** [comment]
Have a look here: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#package-references

**Comment by marcadella** [comment]
Thanks for your answer. The thing is that I don't have any .dacpac for that linked server. Is it somehow possible to tell the tool to ignore missing dependencies for this linked server? I see in the doc  that one can use `SuppressMissingDependenciesErrors`, but it looks like it only works with a package or project reference, but in my case I have none.

**Comment by ErikEJ** [comment]
The approach for working with linked servers is a dacpac for the linked server objects  as described here; 

https://www.mssqltips.com/sqlservertip/3331/how-to-use-a-linked-server-in-a-sql-server-database-project/

**Comment by ErikEJ** [comment]
Closing as there are ways to do this.
