### ISSUE TITLE
Improve error messages for validation

### ISSUE THREAD

**Issue by jmezach** [rr-wfm/MSBuild.Sdk.SqlProj#54]
Before the `.dacpac` is written the `DacpacTool` will perform a validation of the model. This can yield errors and warnings which are currently written to the console. These are picked up by Visual Studio and show up in the Errors List as you would expected. However, they are not correlated to the source file nor the source location on which the error occurs. This data is probably available in the `Validate` method on the `PackageBuilder`, but we simply don't expose it properly.

**Comment by ErikEJ** [comment]
I will have a look.

**Comment by ErikEJ** [comment]
Need to investigate the difference between GetErrors() and Validate
