### ISSUE TITLE
Enable analyzer build warnings as errors to be based on a wildcard

### ISSUE THREAD

**Issue by ErikEJ** [rr-wfm/MSBuild.Sdk.SqlProj#546]
for example: `+!SqlServer.Rules.*`
or `+!SqlServer.Rules.SRN*`

**Comment by cjakobsen** [comment]
Could even expand this to generally change severity to something else like `information` or `suggestion`

**Comment by ErikEJ** [comment]
@cjakobsen Suggestion for the format? (I have not heard of suggestion as a level)

**Comment by cjakobsen** [comment]
Format could be something like `+!SqlServer.Rules.*=suggestion`.

Reference: [Configuration options for code analysis - Severity](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#severity-level)

**Comment by ErikEJ** [comment]
Only warning and error is supported, unfortunately: 

https://learn.microsoft.com/it-ch/dotnet/api/microsoft.sqlserver.dac.codeanalysis.sqlruleproblemseverity?view=sql-dacfx-161 

https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-diagnostic-format-for-tasks?view=vs-2022

**Comment by ErikEJ** [comment]
@cjakobsen PR here: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/547
