### ISSUE TITLE
After Upgrade to 2.7.x unrelated csharp diagnostic errors for sql code

### ISSUE THREAD

**Issue by samtrion** [rr-wfm/MSBuild.Sdk.SqlProj#556]
After upgrading to `MSBuild.Sdk.SqlProj` version 2.7.x from 2.6.1 we get a hole bunch of unrelated csharp diagnostic errors.

![image](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/3283596/8653b00e-2fa4-4135-aa8b-2ac6b1ca6cc4)

All of these diagnostic findings point to a `<name>.sql` file and the sql scripts.

**Comment by ErikEJ** [comment]
@samtrion What was the rot cause?

**Comment by samtrion** [comment]
@ErikEJ Shortly, the schema from `database.csproj` will no longer be taken into account when `database.testvalues.csproj` is builded, although the reference and all contents are unchanged. With the exception of the line Project.

`<Project Sdk="MSBuild.Sdk.SqlProj/2.6.1">` -> `<Project Sdk="MSBuild.Sdk.SqlProj/2.7.2">`

If necessary, I will open a separate bug/issue for this.

**Comment by samtrion** [comment]
But this topic is totally unrelated, because we had a miss configuration with `<Compile Include="HelperScripts\**" />`

**Comment by samtrion** [comment]
Opened another issue https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/557 for the described problem
