### ISSUE TITLE
request: The current SDK bundles target framework '8.0' which is not supported by MSBuild.Sdk.SqlProj. 

### ISSUE THREAD

**Issue by samchoudry** [rr-wfm/MSBuild.Sdk.SqlProj#560]
Currently updating from .net 6 to .net 8 and receive error message MSBuild.Sdk.SqlProj is not supported beyond .6? Any fix for this?

**Comment by ErikEJ** [comment]
Which SDK version do you use? As you can see in the readme,  latest is 2.7.2

**Comment by samchoudry** [comment]
Thank you - updated.
________________________________
From: Erik Ejlskov Jensen ***@***.***>
Sent: Monday, May 20, 2024 11:41 AM
To: rr-wfm/MSBuild.Sdk.SqlProj ***@***.***>
Cc: Sam Choudry ***@***.***>; Author ***@***.***>
Subject: [External]Re: [rr-wfm/MSBuild.Sdk.SqlProj] request: The current SDK bundles target framework '8.0' which is not supported by MSBuild.Sdk.SqlProj. (Issue #560)

 ==> External Email : Use Caution with Links and Attachments <==

Which SDK version do you use? As you can see in the readme, latest is 2.7.2

**Comment by ErikEJ** [comment]
Assume you are unblocked now?
