### ISSUE TITLE
Using SqlCmdVariable in include statements during build time

### ISSUE THREAD

**Issue by sarvasana** [rr-wfm/MSBuild.Sdk.SqlProj#570]
Example:
:r ./folder_a/$(environment_shortname)/dbo.bogus.sql
:r ./folder_b/$(environment_shortname)/dbo.foo.sql

Is this possible and if so, how and where do I declare the variable?

**Comment by ErikEJ** [comment]
According to [this](https://stackoverflow.com/questions/37143638/how-can-i-conditionally-include-large-scripts-in-my-ssdt-post-deployment-script) it is not possible, and there are suggestions for other ways to achieve this
