### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by bheemvennapureddy** [rr-wfm/MSBuild.Sdk.SqlProj#571]
Anything before the digits the slashes are not working ( both back and forward slashes )

<img width="985" alt="Screenshot 2024-07-03 at 11 27 02 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/30b32d58-c9a9-4342-9fc4-0630c5454817">

**Comment by bheemvennapureddy** [comment]
<img width="541" alt="Screenshot 2024-07-03 at 11 28 55 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/2a7aa6e0-b77a-4723-8e6a-2f94d8845d90">

**Comment by bheemvennapureddy** [comment]
@jmezach  Can i get some thoughts on this ?

**Comment by bheemvennapureddy** [comment]
<img width="827" alt="Screenshot 2024-07-03 at 11 34 56 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/040e0023-0723-47c1-b4b4-168e39357202">

**Comment by bheemvennapureddy** [comment]
<img width="539" alt="Screenshot 2024-07-03 at 11 36 10 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/e7d2c5ac-c551-4957-b04f-622f5d428db9">

**Comment by bheemvennapureddy** [comment]
the reference inside the sql file was forward slash instead of backward - got that corrected but `:r` reference fails with sql150 
<img width="745" alt="Screenshot 2024-07-03 at 11 44 48 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/75367be8-28c4-4be6-801b-6a4e4a200851">

**Comment by bheemvennapureddy** [comment]
<img width="1425" alt="Screenshot 2024-07-03 at 11 45 21 PM" src="https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/assets/144472943/c8908b91-2f49-418b-a9b6-8ab063abaf79">

**Comment by ErikEJ** [comment]
Please share a full repro project, NOT  screenshots.

**Comment by bheemvennapureddy** [comment]
I will probably close open a clean one
