### ISSUE TITLE
Inline IGNORE comments for SqlServer.Rules are being ignored

### ISSUE THREAD

**Issue by medianick** [rr-wfm/MSBuild.Sdk.SqlProj#578]
After upgrading to 2.7.1, I enabled code analysis via `<RunSqlCodeAnalysis>True</RunSqlCodeAnalysis>`. Following the SqlServer.Rules [documentation](https://github.com/tcartwright/SqlServer.Rules/blob/master/docs/ignoring_rules.md), I initially added ignored rules via the .csproj file, such as this: `<CodeAnalysisRules>-SqlServer.Rules.SRD0002</CodeAnalysisRules>`, and this worked; however, when moving into the specific SQL file in question (and removing from the .csproj), the rule started being enforced again (not ignored). I tried all the forms of inline syntax. Here's a simple example of a file:

```sql
-- IGNORE SRD0002
CREATE TABLE [dbo].[Version]
(
    [Current] NVARCHAR(100) NOT NULL
)
```

This should be ignoring the [SRD0002](https://github.com/tcartwright/SqlServer.Rules/blob/master/docs/Design/SRD0002.md) rule; however, it still shows up when building the project:

![image](https://github.com/user-attachments/assets/1454dc73-d79a-493d-a932-71716863db3e)

If I add this back into the .csproj (as shown above), it goes back to correctly ignoring this.

If this is in fact an issue with SqlServer.Rules I can report the issue there instead, but thought I would start here as I'm unfamiliar with how these rules and their ignore mechanisms are integrated into this project.

**Comment by ErikEJ** [comment]
I maintain a fork of SqlServer.Rules, with some updated rules and the TSqlSmells rules incorporated and I publish a couple of Nuget packages with the compiled rules.
According to the [docs](https://github.com/tcartwright/SqlServer.Rules/blob/master/docs/Design/SRD0002.md) that rule is not ignorable...

**Comment by medianick** [comment]
> I maintain a fork of SqlServer.Rules, with some updated rules and the TSqlSmells rules incorporated and I publish a couple of Nuget packages with the compiled rules. According to the [docs](https://github.com/tcartwright/SqlServer.Rules/blob/master/docs/Design/SRD0002.md) that rule is not ignorable...

Putting aside the merits of making that not ignorable (there are some use cases for [heap tables](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/heaps-tables-without-clustered-indexes?view=sql-server-ver16), which I'm aware are technically different from tables lacking a primary key), it _does_ seem to be ignorable if done so at the project level, which is arguably worse than allowing a file-level exception to be made.

**Comment by ErikEJ** [comment]
@medianick any suggestions via a PR or discussion in my fork would be highly appreciated

**Comment by ErikEJ** [comment]
@medianick I just discovered that DaacFX codeanalysis support a XML file for exclusions: https://learn.microsoft.com/en-us/sql/tools/sql-database-projects/concepts/sql-code-analysis/sql-code-analysis?view=sql-server-ver16&pivots=sq1-visual-studio#sql-project-file-sample-and-syntax. Not really sure where it must be placed to be picked up, but mayb just together with the .dacpac being analyzed

**Comment by medianick** [comment]
Given the content of the sample file in Microsoft's document -- this is a file-level exclusion of a specific rule -- I would guess that it's meant to be placed in the same folder as the .sql file in question (and included in the project, probably as a Build resource). In fact, given the relative path inside the file, it would likely work wherever it's located as long as it's built into the assembly.

**Comment by ErikEJ** [comment]
I should be placed at the project root. Let me have a play...

**Comment by ErikEJ** [comment]
Had a look, could not make it work (not even in SSDT project) - let me know if you manage to make it work in a classic .sqlproj

**Comment by ErikEJ** [comment]
@medianick This feature is now included   in the latest preview release https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/3.0.0-beta.2

**Comment by medianick** [comment]
> @medianick This feature is now included in the latest preview release https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/3.0.0-beta.2

That's great, thanks @ErikEJ. I'll test it out. I'll be especially interested to see whether it works correctly in a Linux-based system.

**Comment by ErikEJ** [comment]
@medianick me too, seems to be picky with path resolution.

**Comment by medianick** [comment]
For what it's worth, @ErikEJ, I can't the suppression to work even locally on Windows. I've tried both forward and backward slashes as well as locating the `StaticCodeAnalysis.SuppressMessages.xml` file at the solution root as well as the project root (for my MSBuild.Sdk.SqlProj-based project). I still get the warning.

The only difference I can see with my setup compared to your example is that, in my case, the .sql files are located under a different parent folder (since I still maintain them under their original .sqlproj project and so I include them via relative paths in the SDK-based project). So, my FilePath starts with `..\`. But absolute paths (starting from `C:\`) don't work either.

I should add that it does seem to be picking up the suppressor file and identifying the rule being suppressed; it just continues to issue the warning anyway.

**Comment by ErikEJ** [comment]
I think it might only work with files present under your SDK project (looking at the decompiled source). 

Try reversing the link.

The file should be in your project root, as documented.

**Comment by ErikEJ** [comment]
If the suppressor is in use, we show it in the build log.

**Comment by medianick** [comment]
I'll try a few other permutations. The SQL file is included in the SDK project via relative path with wildcard (e.g., `..\ SomeOtherFolder\*.sql`) and I used the same approach in the suppression file, albeit without the wildcard, since a specific file was needed. Do you think it's using a mechanism that wouldn't traverse a path with `..\` and it truly must be under the same root folder?

I can see the suppression occurring in the build log; the warning (SRD002, in this case) is still issued anyway.

**Comment by ErikEJ** [comment]
It must truly be under the project folder. 

And the listing of the rules to be ignored just indicates that the .xml file was found

**Comment by medianick** [comment]
Alas, that won't work for our current approach, where the .sql files are pulled in from their legacy .sqlproj location. (We retain the legacy project for its Intellisense tooling in VS, but perhaps it's time to abandon that now...)

**Comment by ErikEJ** [comment]
@medianick as I wrote above, you can just revert the Dependency, so your legacy .sqlproj links to the files in the MsBuild project

**Comment by medianick** [comment]
Ah, I didn't realize that's what you meant. I'll give that a try!
