### ISSUE TITLE
Question : why csproj or fsproj as project extensions over sqlproj

### ISSUE THREAD

**Issue by bheemvennapureddy** [rr-wfm/MSBuild.Sdk.SqlProj#580]
Sqlproj gets the job done as well so why csproj  or fsproj ?

**Comment by jeffrosenberg** [comment]
That's covered in our readme:

> It provides much of the same functionality as the SQL Server Data Tools .sqlproj project format, but is built on top of the new SDK-style projects that were first introduced in Visual Studio 2017.

We don't have control over the file formats, and the platform doesn't provide the ability to extend .sqlproj files. 

You can still use .sqlproj files side-by-side; again, please more information is available in the readme.
