### ISSUE TITLE
[Idea] .NET Aspire Integration

### ISSUE THREAD

**Issue by jmezach** [rr-wfm/MSBuild.Sdk.SqlProj#584]
I just had a completely random thought that perhaps could be interesting. Would it be useful to have some kind of integration with .NET Aspire where one could spin up a SQL Server container and deploy a MSBuild.Sdk.SqlProj project to it.

Definitely interested in what @jeffrosenberg and @ErikEJ think, but if you're a user of this project please let us know if this would be interesting 🤔

**Comment by ErikEJ** [comment]
Yeah, I have been thinking the same, some kind if synergy here seems useful.

**Comment by jmezach** [comment]
Perhaps something like:

```csharp
var databaseProject = builder.AddProject<Projects.MyDatabaseProject>();
var db = builder.AddSqlServer("sql")
                           .AddDatabase("db")
                           .WithDatabaseProject(dacpac)
```

Which would then result in a running SQL Server container named `sql` with a database named `db` and the referenced database project deployed to it.

**Comment by ErikEJ** [comment]
Do you mean WithDatabaseProject(databaseproject) ?

**Comment by jmezach** [comment]
That would be the main API yes. Of course the hard part is figuring out what that is going to do. It would probably involve running sqlpackage somehow. Not sure if that is included in the SQL containers though

**Comment by ErikEJ** [comment]
Sqlpackage is easy to install:

dotnet tool install Microsoft.SqlPackage

With a connection string, would it be needed inside the container? (It only runs on certain Linux distributions)

**Comment by jmezach** [comment]
I guess we could use a locally installed sqlpackage. We can get the connection string from the SQL resource and I'm guessing we can get the path to the dacpac from the project resource. If we can put those together we can make it work.

Might be able to throw some early prototype together on Friday.

**Comment by ErikEJ** [comment]
I have been thinking about ASPIRE0004 and reading about resource references in the apphost.

Maybe what we really want to do is some thing like this?

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddSqlServer("sql")
            .AddDatabase("test")
            .WithDaccpac("MyDacpac");

builder.Build().Run();
```

The WithDacpac extension method then has some clever ways of finding the location the relevant dacpac and publishing it.

Could be a .dacpac included as content, even pointing to another folder in the solution?

Or a .nupkg with a .dacpac created by MsBuild.SDK .SqlProj

```xml
  <ItemGroup>
    <Content Include="MyDacpac.dacpac">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

Doing this does not break the apphost build:

`<PackageReference Include="MyDacpac" Version="2429.0.4" />`

**Comment by jmezach** [comment]
I can see the use case of having an arbitrary `.dacpac` file somewhere on disk and being able to publish that. I think we could add another extension method that would allow you to just specify the path to the `.dacpac` directly.

Being able to reference a NuGet package build by `MSBuild.Sdk.SqlProj` in your AppHost project and deploying that is also interesting and something we could probably easily support.

Not so sure if it makes much sense though when your `MSBuild.Sdk.SqlProj` is in the same solution as your AppHost project. It feels to me like overkill to have to first package up your project into a NuGet package and then reference that. Will also slow down the inner loop imho. Just being able to reference the project from the AppHost and deploying that is a smoother experience I think, except for the warning we're getting.

**Comment by ErikEJ** [comment]
Agree the nuget option seems cumbersome and anti "inner loop"

**Comment by ErikEJ** [comment]
Stumbled upon this: https://github.com/dotnet/aspire/discussions/1696 - I think we are not blocked in the same manner.

**Comment by ErikEJ** [comment]
And this from one of the Aspire architects: https://github.com/dotnet/aspire/issues/2511#issuecomment-2044245914

**Comment by ErikEJ** [comment]
@jmezach Time to close this 🥳 ??

**Comment by jmezach** [comment]
@ErikEJ Yes!

We have decided to add this integration to the [CommunityToolkit for Aspire](https://github.com/CommunityToolkit/Aspire). Thanks to everyone who has helped us shape this feature. We highly recommend migrating to the [CommunityToolkit version](https://www.nuget.org/packages/CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects/) of this integration.
