### ISSUE TITLE
[Question]: Visual Studio challenges 

### ISSUE THREAD

**Issue by bheemvennapureddy** [rr-wfm/MSBuild.Sdk.SqlProj#586]
Team - Anyone else facing issues with Visual Studio when you this package ?

<img width="675" alt="Screenshot 2024-07-19 at 12 11 12 PM" src="https://github.com/user-attachments/assets/4c50eca0-e776-4378-95a9-5116500ab1eb">

When we load this project we see this notification.

if we accept net4.8 Visual studio adds a bunch of sqlproj files any insights on this 

do we need to still do this ? https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/41

**Comment by bheemvennapureddy** [comment]
<img width="769" alt="Screenshot 2024-07-19 at 4 36 57 PM" src="https://github.com/user-attachments/assets/8ee4c9cd-f7ba-4f65-b756-49da1a599f90">

Here are some example files what visual studio adds

**Comment by ErikEJ** [comment]
That is not a.project related to this SDK. This project type targets .netstandard 2.0 - and you are not sharing any info about the project.

**Comment by bheemvennapureddy** [comment]
To leverage Visual Studio publish ability do we need to have a side loaded project with a sqlproj ?

**Comment by ErikEJ** [comment]
Yes, or you can use "dotnet publish" for inner loop or sqlpackage
