### ISSUE TITLE
Should we consider removing me as a collaborator?

### ISSUE THREAD

**Issue by jeffrosenberg** [rr-wfm/MSBuild.Sdk.SqlProj#590]
Hey @jmezach @ErikEJ - as you may have noticed, I haven't been active around here for quite some time. I'm in a different job that isn't related to this project, and managing two teenagers at home, so I haven't found much time to get involved recently. 

I wanted to check in to see whether this was causing any problems. I've really enjoyed working on the project, and I hope to be able to dig back in at some point, but I don't want to get in the way in the meantime. If it would be easier to remove me, just let me know!

(Also, sorry if there's a better channel I could use for this discussion, but I didn't see one!)

**Comment by jmezach** [comment]
@jeffrosenberg First of all, I don't think that your lack of time is causing any problems, at least not for me, so I don't really see a reason to remove you as a collaborator. Of course it would be nice to have more input on PR's, but I think @ErikEJ and me can manage.

**Comment by ErikEJ** [comment]
Agree, appreciate your PR comments and thoughts a lot.

**Comment by jeffrosenberg** [comment]
Alright, thanks both! I'll do my best to keep up with PRs, but feel free to remove me from them if ever needed.
