### ISSUE TITLE
Create a 2.8.0 build

### ISSUE THREAD

**Issue by ErikEJ** [rr-wfm/MSBuild.Sdk.SqlProj#593]
Copy pasting form the readme no longer works, as 2.8.0 has not been released.

- Update of DacFx to 162.3
- support for `dotnet pack` without requiring a .nuspec file

**Comment by ErikEJ** [comment]
@jmezach ^^

**Comment by jmezach** [comment]
Oops, forgot about that. I'll create a 2.8.0 release branch now.

**Comment by ErikEJ** [comment]
No worries and thanks a lot! 🎉

**Comment by jmezach** [comment]
2.8.0 is up on NuGet now

**Comment by ErikEJ** [comment]
> Perhaps we should document the release process so that everybody can do it ;).

That would be great!
