### ISSUE TITLE
Non-default dynamic data masking operations not supported for date

### ISSUE THREAD

**Issue by Thorium** [rr-wfm/MSBuild.Sdk.SqlProj#594]
I'm trying to have a table with data-masking of day so that data-analyst can see person's age but not private information like full date of birth. ("XX May 2024")

Specification:
https://learn.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver16#define-a-dynamic-data-mask

This standard says it should be `datetime("D")` and it does works in SQL-server but not with SSDT compilation.
```sql
CREATE TABLE [Person] (
[DateOfBirth]  DATE MASKED WITH (FUNCTION = 'datetime("D")') NOT NULL
)
```

Trying to compile that with this project, raises:
`Error (active)	SQL70630	The data masking function provided for column DateOfBirth is invalid.`

**Comment by ErikEJ** [comment]
@Thorium Are you saying this works in .sqlproj project?

**Comment by Thorium** [comment]
I'm not saying that.
However the original issue should have been fixed here: https://github.com/microsoft/sqlmanagementobjects/issues/117

**Comment by ErikEJ** [comment]
Which SDK version do you use (header of your. csproj file) ?

**Comment by Thorium** [comment]
MSBuild.Sdk.SqlProj/2.7.1

But I can change it to any working one, if that would help.

**Comment by ErikEJ** [comment]
We only support the latest which is 2.8.0 (released yesterday)

**Comment by Thorium** [comment]
Updated to 2.8.0.
Still not working.

**Comment by ErikEJ** [comment]
@Thorium Also, DacFX does not use SMO - so a fix there does not affect DacFX

**Comment by ErikEJ** [comment]
@Thorium OK, you need to report this here  https://github.com/microsoft/DacFx

**Comment by Thorium** [comment]
Thanks, opened https://github.com/microsoft/DacFx/issues/476
