### ISSUE TITLE
Release 2.8.1

### ISSUE THREAD

**Issue by ErikEJ** [rr-wfm/MSBuild.Sdk.SqlProj#612]
@jmezach Possible to get it released - has: https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/598

**Comment by jmezach** [comment]
Hmm, it looks like there's a problem with the versioning. I bumped the version number to 2.8.1, but somehow it still produces 2.8.0.

**Comment by jmezach** [comment]
Oh, nevermind, fixed it now. Changed the wrong file apparently.

**Comment by jmezach** [comment]
2.8.1 is up on NuGet.org now.
