### ISSUE TITLE
DacpacToolCommand fails

### ISSUE THREAD

**Issue by Thorium** [rr-wfm/MSBuild.Sdk.SqlProj#618]
My dotnet.exe build of SSDT project is failing for:
```
C:\Users\Me\.nuget\packages\msbuild.sdk.sqlproj\2.8.1\Sdk\Sdk.targets(173,5): error MSB3073: The command "..." exited with code 9009. [C:\repo\AdventureWorks_SSDT\AdventureWorks_SSDT.fsproj]
```

9009 is file not found, but the files are there.
So I open the file, Sdk.targets, the line is `<Exec Command="$(DacpacToolCommand)" ` and above is a low-prio message, I set it to high, to see the message. It says:

```
  Running command: dotnet "C:\Users\Me\.nuget\packages\msbuild.sdk.sqlproj\2.8.1\Sdk\../tools/net6.0/DacpacTool.dll" collect-includes
  'dotnet' is not recognized as an internal or external command,
  operable program or batch file.
```
Ok, so either dotnet is not found (which is very weird, as it's in the path):
```
C:\repo>dotnet --version
 8.0.400
```
...or mixing the \ and / are messing something. Also the file is there:
```
Directory of C:\Users\Me\.nuget\packages\msbuild.sdk.sqlproj\2.8.1\tools\net6.0
26/08/2024  14:17           225,280 DacpacTool.dll
```

I see this first time today (after some Windows updates of course). VisualStudio 2022 builds the dacpac just fine. Any ideas what could it be?

**Comment by Thorium** [comment]
The SSDT project is here:
https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/MsSqlSsdt/MsSqlSsdt.Tests/AdventureWorks_SSDT/AdventureWorks_SSDT.fsproj
...and even if I remove about all and rip it to bare minimum, it still fails. And the same success on CI. So I expect there is something wrong with my machine.

**Comment by ErikEJ** [comment]
That is an very old SDK version. Could you please try with 2.8.1

**Comment by Thorium** [comment]
Yes, I'm locally running on 2.8.1 which having this issue (not pushed to GitHub as it's broken!)
I don't know if the issue exists in the old one, but I tested with 2.7.1 also and it had it, so this is not regression.

**Comment by ErikEJ** [comment]
Ah! You should target netstandard2.0, not net6.0 as stated in our docs

**Comment by Thorium** [comment]
Thanks, but didn't help...
```
  Running command: dotnet "C:\Users\Me\.nuget\packages\msbuild.sdk.sqlproj\2.8.1\Sdk\../tools/net8.0/DacpacTool.dll" collect-includes
  'dotnet' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\Me\.nuget\packages\msbuild.sdk.sqlproj\2.8.1\Sdk\Sdk.targets(173,5): error MSB3073: The command "..." exited with code 9009. [C:\repo\AdventureWorks_SSDT\AdventureWorks_SSDT.fsproj]
```
If I run the command manually, it has no output (and no error). Thus I expect my build tool (MSBuild or whatever) somehow don't transfer some the environment variables (e.g. path) properly. Then when it sees "dotnet" in Sdk.targets(173,5) it cannot do it. 

But I found a weird workaround: Don't use the "Developer Command Prompt for VS2022" instead use local cmd.exe and it works! It must be that the latest VS2022 updated developer variables are somehow messed in my computer.
