### ISSUE TITLE
How to deploy on a server with non-standard TCP port (1433).

### ISSUE THREAD

**Issue by axelgenus** [rr-wfm/MSBuild.Sdk.SqlProj#62]
I've tried different combination but it seems like "dotnet publish" does not support specifying the server port to use for deployment. Is there any specific syntax to use?

What I tried:

/p:TargetServerName="localhost,5000"
/p:TargetServerName="localhost:5000"
/p:TargetServerName="(localhost,5000)"

All returns:

```
MSBUILD : error MSB1006: Property is not valid.
Switch: 1433
```

Also I tried looking for a "TargetServerPort" in the project source code to no avail.

**Comment by axelgenus** [comment]
Sorry, I just found out that this issue is actually related to MSBuild (see https://github.com/dotnet/msbuild/issues/2999).

This is actually feasible escaping the double quotes like this:

/p:TargetServerName=\"localhost,5000\"

**Comment by jmezach** [comment]
@axelgenus Glad to hear you've managed to resolve this. Perhaps we should add this to the docs.
