### ISSUE TITLE
How to set value of Name tag in DacMetadata.xml file ?

### ISSUE THREAD

**Issue by AlexETF** [rr-wfm/MSBuild.Sdk.SqlProj#626]
How to set value of Name tag in DacMetadata.xml file in DACPAC file ? I managed to set name of the output .dacpac when it is built by setting the property \<AssemblyName\>, but value in DacMetadata.xml is still the project name. 

I tried setting properties:
Name, OutputAssembly, TargetName, SqlTargetName, RootNamespace, DacpacName
but none of this affected the value in DacMetadata.xml.

Is there a way to set Name via project file ?

My environment SDK: MSBuild.Sdk.SqlProj/2.6.0

**Comment by jmezach** [comment]
I did some digging and it looks like we are using the built-in MSBuild property called `MSBuildProjectName` as the name of the package. This should be the name of the `.csproj` file without the extension. So renaming your project file should result in a different Name tag in the `DacMetadata.xml`.

**Comment by jmezach** [comment]
Is there a reason you would want these to be different? At least now there is a bit of traceability between the project and the resulting `.dacpac`. Adding a separate property for this would be trivial, but it is an additional things to maintain so I'm just wondering what the use case is.

**Comment by ErikEJ** [comment]
@AlexETF Any comments?

**Comment by ErikEJ** [comment]
Closing as no response with additional details explaining the connection between project name, .dacpac name and name tag was provided.

@AlexETF FYI
