### ISSUE TITLE
The check for additional analyzers does not work well

### ISSUE THREAD

**Issue by ErikEJ** [rr-wfm/MSBuild.Sdk.SqlProj#640]
And prevents the warning about missing 3rd party analyzers to appear!

(we get a lot of analyzers imposed via other packages, and Directory.Build.Props...)

`Using additional analyzers: C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll, C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll, C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll, C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.Fixes.dll, C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll, C:\Program Files\dotnet\sdk\8.0.401\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.Fixes.dll, C:\Users\user\.nuget\packages\asyncfixer\1.6.0\analyzers\dotnet\cs\AsyncFixer.dll, C:\Users\user\.nuget\packages\meziantou.analyzer\2.0.169\analyzers\dotnet\roslyn4.8\cs\Meziantou.Analyzer.CodeFixers.dll, C:\Users\user\.nuget\packages\meziantou.analyzer\2.0.169\analyzers\dotnet\roslyn4.8\cs\Meziantou.Analyzer.dll, C:\Users\user\.nuget\packages\securitycodescan.vs2019\5.6.7\analyzers\dotnet\SecurityCodeScan.VS2019.dll, C:\Users\user\.nuget\packages\securitycodescan.vs2019\5.6.7\analyzers\dotnet\YamlDotNet.dll, C:\Users\user\.nuget\packages\sonaranalyzer.csharp\9.32.0.97167\analyzers\Google.Protobuf.dll, C:\Users\user\.nuget\packages\sonaranalyzer.csharp\9.32.0.97167\analyzers\SonarAnalyzer.CFG.dll, C:\Users\user\.nuget\packages\sonaranalyzer.csharp\9.32.0.97167\analyzers\SonarAnalyzer.CSharp.dll, C:\Users\user\.nuget\packages\sonaranalyzer.csharp\9.32.0.97167\analyzers\SonarAnalyzer.ShimLayer.dll, C:\Users\user\.nuget\packages\sonaranalyzer.csharp\9.32.0.97167\analyzers\SonarAnalyzer.dll, C:\Users\user\.nuget\packages\stylecop.analyzers.unstable\1.2.0.556\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll, C:\Users\user\.nuget\packages\stylecop.analyzers.unstable\1.2.0.556\analyzers\dotnet\cs\StyleCop.Analyzers.dll
`

**Comment by jmezach** [comment]
I'm sorry, but what is the issue here exactly? Just trying to understand this ;).

**Comment by ErikEJ** [comment]
I had a check to create a  build warning if only the built in analyzers were present, but this check is not working, as all .net analyzers are also passed in..

Have to think about how to fix this..
