### ISSUE TITLE
Change Name of DACPAC Output

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#65]
In my `.csproj`, `<TargetDatabaseName>DBName</TargetDatabaseName>` determines what my database will be called when I run `dotnet publish`. It doesn't influence what the the `dacpac` file is named when I run `dotnet build`. How can I change the name of the `dacpac`?

**Comment by jmezach** [comment]
From what I've heard from @RVink you should be able to set `AssemblyName` in the project file and that will override the name of the resulting `.dacpac`. I do realise that this is a bit confusing, so perhaps we should have a separate property for it instead.

By default though, we use the name of the project file as the name of the `.dacpac` so you can also try renaming your project file to whatever you want the `.dacpac` to be named.

**Comment by brettrowberry** [comment]
I was aware the project name determines the name of the `.dacpac`. The `AssemblyName` in the project file worked! I will send a PR for the `README` to explain this. Thanks!

**Comment by RVink** [comment]
It's indeed possible to change the output name by setting the `AssemblyName` in the project file. However it breaks the `dotnet publish` command. I created #68 for this issue
