### ISSUE TITLE
Dry run/ logs on changes made by publishes

### ISSUE THREAD

**Issue by djluck** [rr-wfm/MSBuild.Sdk.SqlProj#69]
`dotnet publish [my_db.sqlproj]` works well in local development but I'm a little wary of pointing it at our production environment, mostly because there seems to be no method of either previewing the changes that the publish command will make nor is there no log of the changes made.
Is there an option I can configure to get access to this functionality? If not, what would be required to implement such functionality? Depending on the volume/ complexity of work, it's something I might be able to take on.

P.s. I'd like to thank you guys for putting this project out here- it's so far solved a big pain point in an ongoing .net core migration.

**Comment by ErikEJ** [comment]
You can use sqlpackage /DeployReport https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#help-for-deployreport-action

**Comment by djluck** [comment]
Thanks Erik but I'm interested in running deployments (and any change reporting) on Linux- is sqlpackage.exe cross platform?

**Comment by jmezach** [comment]
@djluck Yes, SqlPackage is available cross-platform. See here for more details: https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15

**Comment by djluck** [comment]
Wonderful, thanks guys- I saw the .exe extension and feared it would be windows only.
