### ISSUE TITLE
Deploying to older version of SQL Server error message is not clear

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#70]
I have a SQL Server 2016 database server.
I have a project file that includes `<SqlServerVersion>Sql130</SqlServerVersion>`.
`dotnet publish` works great!

`Sql120` also works. However, with `Sql140`, publishing fails with this error message. It's not obvious that it is due to a version mismatch.

```
EXEC : error : Deployment of database 'Prediction' failed: An error occurred during deployment plan generation. Deployment cannot continue. [C:\dev\Prediction\Prediction.fsproj]
C:\Users\User\.nuget\packages\msbuild.sdk.sqlproj\1.8.1\Sdk\Sdk.targets(220,5): error MSB3073: The command "dotnet "C:\Users\User\.nuget\packages\msbuild.sdk.sqlproj\1.8.1\Sdk\../tools/netcoreapp3.1/DacpacTool.dll" deploy -i "C:\dev\Prediction\bin\Debug\netstandard2.0\/Prediction.dacpac" -tsn "localhost\MyServer" -tdn "Prediction"   -p IncludeCompositeObjects=true  " exited with code -1. [C:\dev\Prediction\Prediction.fsproj]
```

**Comment by jmezach** [comment]
Yes I noticed that the error messages being reported when the deployment is failing doesn't give the user much to go on. In fact when I was recording the dotnetFlix episode mentioned in the README I experienced this exact same problem.

I'm not sure what we can do about this. I think we'll need to do some digging to figure out if we can get more details about what's going wrong. I might have some time this weekend.
