### ISSUE TITLE
Adding an assembly registration to DB

### ISSUE THREAD

**Issue by mkzx1** [rr-wfm/MSBuild.Sdk.SqlProj#79]
How do I correctly add an assembly to db project?
For example I have an empty project
```
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <SqlServerVersion>Sql150</SqlServerVersion>
    </PropertyGroup>
</Project>
```
 and I'm trying to create new assembly with sql script
```
CREATE ASSEMBLY [Test]
FROM 0x4D5A90000300000004000000FFFF000....
WITH PERMISSION_SET = UNSAFE
GO
```
when I try to build the project, I receive:
  _AddReference.sql(2, 6): [SQL70557] This assembly is corrupt or not valid._
I have this error with any assembly, I even try the Microsoft.SqlServer.Types.
So I must be doing something wrong.

**Comment by jmezach** [comment]
@mkzx1 We don't currently support SQLCLR assemblies with this project (as noted in the [README](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/blob/master/README.md). Personally I have no experience with SQLCLR so I don't think I'm in the best position to help with this.

I am curious to understand your scenario's though. Could you elaborate a little bit about why you'd like this to work?

**Comment by mkzx1** [comment]
@jmezach We use some custom encryption library, and in DB we use user defined types from this library.
