### ISSUE TITLE
add topic hacktoberfest

### ISSUE THREAD

**Issue by lastlink** [rr-wfm/MSBuild.Sdk.SqlProj#83]
Could we get the topic/tag **hacktoberfest** added to this repository so that pull requests merged during october get credited and attention drawn to this repository.

See https://github.com/topics/hacktoberfest and https://hacktoberfest.digitalocean.com/faq

===
Please at me @GoEddie so I receive a notification

**Comment by GoEddie** [comment]
Happy to add it but if you are doing it just for October fest better find another repo as I won’t have time to review any changes before next week.

Probably the 2nd nov will be my first chance so I didn’t want to raise your hopes :)

**Comment by jmezach** [comment]
@lastlink @GoEddie We already have that topic added to this repository, so I'm not quite sure what more we can do here.

**Comment by GoEddie** [comment]
Hang on I thought this was a different repo! This is nothing to do with me :)

**Comment by jmezach** [comment]
;) I think we can close this then.
