### ISSUE TITLE
Pass SQLCMD variable with dotnet publish

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#84]
I believe it’s possible to pass the value of a SQLCMD variable with `dotnet publish`. What’s the syntax?

**Comment by jmezach** [comment]
@brettrowberry I guess it depends on how you've setup your SQLCMD variables in your project file. For example, let's consider the following example:

```xml
    <SqlCmdVariable Include="TasksDb">
      <DefaultValue>Tasks</DefaultValue>
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
```

In this scenario you should be able to set `SqlCmdVar__1` from the command line using `dotnet publish /p:SqlCmdVar__1=SomeValue`. This should set the `TaskDb` SQLCMD variable to the value `SomeValue` at deployment time.

Please note that currently we don't use the `DefaultValue`. So in this scenario, if you do not specify `SqlCmdVar__1` on the command line it will have no value (unless it is specified in the project file somewhere). If this is something you need I suggest opening a separate issue for that.

@ErikEJ @jeffrosenberg Perhaps we should add this to the docs?

**Comment by brettrowberry** [comment]
> In this scenario you should be able to set SqlCmdVar__1 from the command line using dotnet publish /p:SqlCmdVar__1=SomeValue.

This exactly solved my issue! I definitely think this should be added to the docs. I can put together a PR if you like.

> Please note that currently we don't use the `DefaultValue`. So in this scenario, if you do not specify SqlCmdVar__1 on the command line it will have no value (unless it is specified in the project file somewhere).

That's what I was seeing. That's something I didn't notice in the docs (it might have been there, bit I missed it anyway). I think the `<DefaultValue>SomeValue</DefaultValue>` should be omitted from docs/samples if it isn't supported.

> If this is something you need I suggest opening a separate issue for that.

I'm not sure if I need `DefaultValue`. It was being ignored and I couldn't figure out how to pass it in - but now I know how to pass it in. Then, looking though some of the scripts in my project, it turns out that I didn't need the variable at all and just hardcoded the value (doesn't need to be configurable).

Before I open an issue, is there a reason you decided not to support `DefaultValue` (maybe to encourage people not to put secrets into source code?). I don't have strong opinions on this and it only came up because some legacy project I was converting used `SqlCmdVar` (and now it doesn't). Part of the value of this project is the good opinions you bring to it - which things to include and leave out. You are wise to avoid feature parity with the old `.sqlproj` files.

@ErikEJ @jeffrosenberg Perhaps we should add this to the docs?

**Comment by jmezach** [comment]
@brettrowberry I don't think there's a particular reason not to support the `DefaultValue` option other than not having the time to actually implement it. That being said I feel that you still set a default value in the project file if you want using something like this:

```xml
<PropertyGroup>
  <MySqlCMDVariable Condition="$(MySQLCmdVariable)==''">SomeValue</MySqlCMDVariable>
</PropertyGroup>

<ItemGroup>
  <SqlCmdVariable Include="MySqlCMDVariable" Value="$(MySQLCMDVariable)">
</ItemGroup>
```

> Note I haven't actually tried this, but I'm fairly confident that it will work.

Using this, you can still set an alternate value for that variable if you want by passing it on the command line. We wouldn't have to add support for the `DefaultValue` item metadata this way I think.

**Comment by brettrowberry** [comment]
I tried this out quickly and it worked. I'd like to play with it a little longer and make a PR to add to the `README`.

**Comment by jmezach** [comment]
@brettrowberry As of version 1.11.0 we now support the `DefaultValue` element (or attribute) as a fallback value and it is also explained in the README. Closing this as I don't think there's much more here that we can do.
