### ISSUE TITLE
PostDeploy, Content Remove, and Solution Explorer

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#87]
I have a script, `app_MyApp.sql`, that I would like to use in a `PostDeploy` step.

In order to do that, I used `Content Remove` and `PostDeploy Include` nodes.  

Here is my project file:

``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<TargetServerName>localhost</TargetServerName>
		<TargetName>MyDB</TargetName>
		<TargetDatabaseName>MyDB</TargetDatabaseName>
		<SqlServerVersion>Sql130</SqlServerVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\SQL\**\*.sql" />
		
		<Content Remove="..\SQL\Security\Users\app_MyApp.sql" />
		<PostDeploy Include="..\SQL\Security\Users\app_MyApp.sql" />
	</ItemGroup>

</Project>
```

Doing this removes `app_MyApp.sql` from the tree in Visual Studio's Solution Explorer.

Is there a way to exclude the script from the build while still showing it in the tree?

**Comment by jmezach** [comment]
@brettrowberry Haven't tried it myself, but maybe adding `Visible=True` to the `<Content Remove="..." />` element does the trick?

**Comment by brettrowberry** [comment]
Great suggestion! Unfortunately:
`MSB4162	<Visible> is not valid. Child elements are not allowed below a item remove element.`

**Comment by jmezach** [comment]
@brettrowberry Did you add `Visible` as an attribute on the `<Content>` element or as a child element?

**Comment by brettrowberry** [comment]
``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<TargetServerName>localhost</TargetServerName>
		<TargetName>MyDB</TargetName>
		<TargetDatabaseName>MyDB</TargetDatabaseName>
		<SqlServerVersion>Sql130</SqlServerVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Security\Users\app_LoanPersistor.sql">
			<Visible>false</Visible>
		</Content>
		<PostDeploy Include="Security\Users\app_LoanPersistor.sql" />
	</ItemGroup>

</Project>
```
Throws:
`<Visible> is not valid. Child elements are not allowed below a item remove element.`

``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<TargetServerName>localhost</TargetServerName>
		<TargetName>MyDB</TargetName>
		<TargetDatabaseName>MyDB</TargetDatabaseName>
		<SqlServerVersion>Sql130</SqlServerVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Security\Users\app_MyApp.sql" Visible="true" />
		<PostDeploy Include="Security\Users\app_MyApp.sql" />
	</ItemGroup>

</Project>
```

In both cases, the `Users` folder (and the contained script) do not appear.

![image](https://user-images.githubusercontent.com/10521647/98165324-af106a80-1eb3-11eb-93b4-74fbe78dc609.png)

I guess VS Code users have the upper hand here!

**Comment by jmezach** [comment]
What happens when you keep the Content Remove element (without the Visible attribute) and then add a None element with Include="your-file.sql"?

**Comment by brettrowberry** [comment]
This worked!

``` xml
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<TargetServerName>localhost</TargetServerName>
		<TargetName>MyDB</TargetName>
		<TargetDatabaseName>MyDB</TargetDatabaseName>
		<SqlServerVersion>Sql130</SqlServerVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Security\Users\app_MyApp.sql" />
		<None Include="Security\Users\app_MyApp.sql" />
		<PostDeploy Include="Security\Users\app_MyApp.sql" />
	</ItemGroup>

</Project>
```

**Comment by brettrowberry** [comment]
- `Content` node for removing from build
- `None` node for adding to tree viewer,
- `PostDeploy` node for adding as a postdeploy script

Is this a common enough workflow to document? 
Is this the best way to do this?

**Comment by jmezach** [comment]
Personally i would probably but all my post deployment scripts into the Post-Deployment folder (so that they are excluded from the build by default) and then have a `PostDeploy` script that imports all of them (using the `:r script.sql` syntax). But I guess it's mostly a matter of preference and this will work.

**Comment by brettrowberry** [comment]
I thought when I did that they were included in the build. I’ll give that another try.
