### ISSUE TITLE
Question - Is it possible to exclude Logins\RoleMembership in building dacpac?

### ISSUE THREAD

**Issue by IsaaacD** [rr-wfm/MSBuild.Sdk.SqlProj#92]
Sorry if this is the wrong place, but I'm wondering how we can configure so we don't update or delete any user logins? I'm looking at this SoF thread https://stackoverflow.com/a/43916061 and it seems to offer some guidance but I'm not having any luck getting the dacpac to ignore the items. Any pointers would be appreciated! Thanks.

**Comment by ErikEJ** [comment]
Do you mean building or publishing?

**Comment by jmezach** [comment]
These properties are usually set at deployment time and affect which objects are not deployed, but they will still be part of the `.dacpac`. If you're looking to ignore certain `.sql` files from the `.dacpac` you can change their build action to `None`.

**Comment by IsaaacD** [comment]
I mean for both building and publishing. If I generate a sqlproj from my database and I try to build the solution, it has some issues building because (I suspect) the users are windows users. See below:
![image](https://user-images.githubusercontent.com/5303125/98593385-1574fe80-22a1-11eb-95f8-5a2d469f9237.png)

So the dacpac doesn't get created. If I delete the file wliu.sql the project is building fine, but when I go to import the dacpac produced by the sqlproj it has this in the output: 
![image](https://user-images.githubusercontent.com/5303125/98593664-7ac8ef80-22a1-11eb-9b7c-57d92d64e580.png)
And if I export the upgrade script the dacpac is generating, I indeed see that the user is being dropped.

I'd like to have the project build in VS without the permissions so the produced dacpac doesn't delete any users in the database if that makes sense. If there's some build parameters or a publish profile I could add, I think that would do what I'm after.

**Comment by jeffrosenberg** [comment]
I don't believe the build issue you're seeing is because the users are Windows users, it's because there isn't a requisite login for them. You can fix that by adding a login object for them.

**Comment by IsaaacD** [comment]
Thanks @jeffrosenberg I think you're right there's not the requisite logins, and I'm not even sure if these users are being used if there are no logins. I'm not the DBA and just looking to streamline the process so I can had a dacpac to someone without potentially having downstream issues and causing confusion if someone can't login.

I'm just manually trying to publish the dacpac using [SSMS](https://blogs.msmvps.com/deborahk/deploying-a-dacpac-with-sql-server-management-studio/), it's not a complete process but I'm new to dacpacs and want to have the process pretty cut and dry.

You mentioned, "remove the users from your project altogether, then set the dacpac not to publish users and logins". This is what I'd like to do but I'm not 100% clear on how to do so. Any pointers would be appreciated.

**Comment by jeffrosenberg** [comment]
@IsaaacD one thing I want to clarify before we go too much further here -- are you actually using this SDK as part of your project? I may still be able to help, but I'm starting to get the sense that your question isn't actually related to this particular project. We develop an extension to MSBuild that allows building database projects cross-platform using the SDK-style `.csproj` files, and are not involved with the official Microsoft `.sqlproj` file format.

**Comment by IsaaacD** [comment]
@jeffrosenberg This is a good clarification to make. I have to apologize and say my bad, it appears I actually did create a .sqlproj and I didn't use this SDK. That being said I meant to use this project and was just encountered a PEBKAC error (creating the SQL project in VS UI rather than dotnet CLI).

So, that being said. Taken from this SDK point of view, I see it doesn't produce a dacpac on the build like the sqlproj but I'm still a bit unclear about how I'd exclude the user permissions would it be something as simple as something like in the SoF thread I initially referenced?
```
sqlpackage.exe /p:DropObjectsNotInSource=True 
/p:ExcludeObjectTypes=Users;Logins;RoleMembership;Permissions
```
Or is there something additional I'm missing?
Thanks! And sorry again for any confusion!

**Comment by jeffrosenberg** [comment]
OK, got it, thanks for clarifying. This SDK does produce dacpacs on build, so you're good there. I would recommend deleting the user objects from your database project to eliminate your build errors. How you proceed from there depends on how you're publishing:

- If you use SqlPackage to publish, then yes, you can do something just like what you posted
  - Even more simply, you could also skip the `DropObjectsNotInSource` property, in which case your publishes would only add or update objects, never drop them -- whether this is a reasonable approach really depends on your use case
- You can use this project to publish, in which case those properties can be added to your `.csproj` file, as documented [in the readme](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj#publishing-support)
- Publishing through SSMS isn't ideal, as per the article you posted, it doesn't support advanced options

**Comment by IsaaacD** [comment]
@jeffrosenberg  Thanks again, I think I almost got it. I've added a new project to reference the sql files in my .sqlproj, and this is the resulting .csproj
```
<Project Sdk="MSBuild.Sdk.SqlProj/1.9.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <ExcludeObjectTypes>Users;Logins;RoleMembership;Permissions</ExcludeObjectTypes>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\CorporateWebsite.Sql\dbo\**\*.sql" />    
  </ItemGroup>  
</Project>
```
So this should in theory be what I'm after. I can run  `dotnet build` and it produces a dacpac! But if I import the .dacpac into SSMS it still talks about dropping permissions. Is that a red herring due to the fact SSMS 
> doesn't support advanced options
 
as you had mentioned to? Or am I still building the .dacpac wrong?

**Comment by jeffrosenberg** [comment]
I believe it's because of the advanced options. Since you've added the options to your .csproj file, I'd recommend trying to publish via the `dotnet publish` command. More info on that is available in our readme file.

**Comment by IsaaacD** [comment]
Thanks for your help @jeffrosenberg, `dotnet publish` definitely works as expected. Cheers!

**Comment by jmezach** [comment]
Looks like this issue can be closed, unless @IsaaacD feels we should improve our docs somehow?

**Comment by IsaaacD** [comment]
@jmezach The documentation is good, I just was looking in the wrong place and especially because I was messed up with using a .sqlproj initially
