### ISSUE TITLE
Visual Studio Solution Explorer README.md Addition

### ISSUE THREAD

**Issue by brettrowberry** [rr-wfm/MSBuild.Sdk.SqlProj#94]
There is an unresolved comment from https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/pull/91 about working with Visual Studio's Solution Explorer that wasn't addressed. I plan to address it in a coming PR.

**Comment by jmezach** [comment]
@brettrowberry Do you still plan on creating a PR for this? If not that's fine, just looking for a status update here.

**Comment by ErikEJ** [comment]
Closing this as inactive, feel free to re-open if desired.
