### ISSUE TITLE
[Question] Update object files by comparing project to database

### ISSUE THREAD

**Issue by alexszasz** [rr-wfm/MSBuild.Sdk.SqlProj#95]
Is there a way/plan to support taking changes from a development database and updating the sql files in the project, similar to how it is possible in Windows Visual Studio + SSDT (Schema compare + Update target)

**Comment by jmezach** [comment]
@alexszasz This is more an IDE feature which we currently don't provide. That being said, you should be able to do this from an existing `.sqlproj` on Windows and use that as a "companion" project as described in [this blog post](https://erikej.github.io/efcore/2020/05/11/ssdt-dacpac-netcore.html).

Obviously that will only work on Windows. I do know that Microsoft is working on something for Azure Data Studio which should work cross-platform but I haven't tried it myself yet. Perhaps @ErikEJ can comment on that.

**Comment by ErikEJ** [comment]
The tooling in ADS is very new, and missing many design time features. ADS has a Schema Compare tool, that you can use together with the sqlproj support. 

In addition, you can use sqlpackage /Action:Script to compare a live database with your .dacpac.

https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15#script-parameters-and-properties

I think all these processes are beyond the scope of this build and publish tool, however.

**Comment by jmezach** [comment]
I agree with @ErikEJ that this is beyond the scope of what this project is trying to achieve. We do not currently have any plans to add this.
